### ISSUE TITLE
bug？预览浮图与原图样子不一致

### ISSUE THREAD

**Issue by baibai92** [Mr-VincentW/PhotoShow#10]
反馈一个不知道是不是bug的问题：在pixiv画师主页（每个画师或多或少都有），鼠标移动到某些缩略图显示出来的，与打开图片后显示的并不一致，预览浮图与原图相比，裁剪了一部分画面。我用tampermonkey插件 pixiv previewer没有出现这样的问题，是否两个软件功能不同。

**Comment by Mr-VincentW** [comment]
感谢您的反馈，浮图秀已于下一更新（4.5.4.0）中修复了此问题，敬请期待各应用商店完成审核上架。
