### ISSUE TITLE
Wrong image identified

### ISSUE THREAD

**Issue by Sisyphe42** [Mr-VincentW/PhotoShow#101]
Seems the same bug just fixed in 4.20.1 I think.

Version: 4.20.1
Site: https://www.netsarang.com/en/free-for-home-school/
Xpath: //*[@id="post-352"]/div/div[4]/div/div/div/div[2] identified as //*[@id="post-352"]/div

Maybe ignoring the style of the sub-elements in the strategy could make sense?

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. Can you please provide more details on how to replicate the issue? I couldn't find any image on the link attached.

**Comment by Sisyphe42** [comment]
Yeah there is no image. I mean I can't click the input box.

**Comment by Mr-VincentW** [comment]
This issue has been fixed with update 4.21.0. Thanks.
