### ISSUE TITLE
Support for App Store screenshots

### ISSUE THREAD

**Issue by Kyogre** [Mr-VincentW/PhotoShow#102]
Is it possible to add support to preview screenshots on AppStore pages like https://apps.apple.com/en-us/app/sarcoph/id721911537?
On the screenshot below I marked url of the desired image in page inspector with a red line. Maybe there is even higher quality image's url in the page source code, but I am a bit lazy to inspect deeper :>

![appstore image example](https://user-images.githubusercontent.com/2260980/221367754-03897813-0d4c-42e3-942b-54e1ff3d8f8a.png)

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This has been addressed with update 4.21.0. Cheers.
