### ISSUE TITLE
开启此扩展一些网站菜单无法点击

### ISSUE THREAD

**Issue by nei1ee** [Mr-VincentW/PhotoShow#103]
[Naive UI](https://www.naiveui.com/zh-CN/dark/components/button) 组件页面，左侧菜单选择，打开devtools或者禁用此扩展才可以点击。
[draw.io](draw.io) 左侧图形菜单无法点击其他的，如杂项、UML等。

**Comment by Mr-VincentW** [comment]
感谢反馈。针对您所提供的两个网站，鉴于页面本身几乎没有图片，您可以选择针对此二网站关闭浮图秀。
产生此问题的具体原因可参阅 #29
