### ISSUE TITLE
浮图秀无法保存修改的设置

### ISSUE THREAD

**Issue by LightningLeader** [Mr-VincentW/PhotoShow#104]
您好，我在使用浮图秀的时候会出现无法保存修改设置的情况。
具体来说是，我要将“激活模式”的默认设置修改为“ctrl+鼠标悬停”，在点击“ctrl”之后退出设置窗口，但是没有生效。返回设置窗口发现“激活模式”仍然为默认。这种情况对于其他设置也是一样的，都无法保存。此外“浮图秀已对当前网站启用”这个按钮点击无反应。
希望能够解答我的疑惑，谢谢。

**Comment by Mr-VincentW** [comment]
感谢反馈。浮图秀依赖浏览器账户保存设置信息，所以您需要有一个有效且登录的账户，请确认是否是此原因引起的问题。如有其他问题，欢迎进一步在此追加说明，谢谢。

**Comment by LightningLeader** [comment]
> 感谢反馈。浮图秀依赖浏览器账户保存设置信息，所以您需要有一个有效且登录的账户，请确认是否是此原因引起的问题。如有其他问题，欢迎进一步在此追加说明，谢谢。

应该不是因为没有登录账户导致的。我是在EDGE浏览器上使用的。之前这些功能都是可以保存的，不过之后浏览器出了点问题（插件和扩展全都被删除了），再次重新下载浮图秀后使用就遇到了目前这个问题。

**Comment by Mr-VincentW** [comment]
请问之前您在能正常使用时，有登录浏览器账户吗？

**Comment by LightningLeader** [comment]
> 请问之前您在能正常使用时，有登录浏览器账户吗？

有。我浏览器账户是一直登录的。

**Comment by Mr-VincentW** [comment]
请尝试重新安装浮图秀后重试？

**Comment by LightningLeader** [comment]
> 请尝试重新安装浮图秀后重试？

我重装过很多次，并没有什么效果。不过我对于设置只想要将它的“激活模式”修改为“ctrl+鼠标悬停”和“视图模式”修改为“轻量”，这种可以从源码层面修改吗？

**Comment by Mr-VincentW** [comment]
很抱歉浮图秀不能针对单个用户在源代码层面订制功能，这将影响到所有用户。
从您所描述的问题表现来看，几乎可以肯定是账户同步出了问题。希望这对您排查问题有帮助。

**Comment by LightningLeader** [comment]
> 很抱歉浮图秀不能针对单个用户在源代码层面订制功能，这将影响到所有用户。 从您所描述的问题表现来看，几乎可以肯定是账户同步出了问题。希望这对您排查问题有帮助。

好的，我明白了，我之后会再尝试一下的。谢谢！

**Comment by Mr-VincentW** [comment]
不妨尝试重装浏览器？
