### ISSUE TITLE
能否增加一个开启和停用的快捷键

### ISSUE THREAD

**Issue by i110077** [Mr-VincentW/PhotoShow#105]
目前必须把扩展图标固定到工具栏去点击才能设置，能否像[Image Max URL](https://github.com/qsniyg/maxurl)一样增加一个开启和关闭的快捷键？

**Comment by Mr-VincentW** [comment]
感谢反馈。浮图秀已于更新 4.21.0 中新增快捷键用于针对当前网站启用或关闭浮图秀。默认快捷键为 **`Alt` + `Shift` + `P`**，您可以在如下位置更改按键绑定。
- **Chrome:** chrome://extensions/shortcuts
- **Edge:** edge://extensions/shortcuts
- **Firefox:** about:addons -> PhotoShow -> Manage -> Manage Extension Shortcuts
