### ISSUE TITLE
Breaks kee addon

### ISSUE THREAD

**Issue by Fred-Vatin** [Mr-VincentW/PhotoShow#107]
Firefox | Chrome | OS | Extension
------- | ---- | ---- | ---- 
110.0.1 |  110.0.0.0  | Win 10 21H2 | 4.20.1

On some sites, like google or https://auth.leboncoin.fr/login, where kee find logins, after it autofills I can no longer click on the inputs or the kee icon. I can not manually input or edit my login if I want to, unless I use tab to move focus.
![image](https://user-images.githubusercontent.com/22337329/223776359-ea2088e6-91c9-48b3-bcf2-dab3973358f4.png)
![image](https://user-images.githubusercontent.com/22337329/223776376-697566da-33b8-48fa-86d7-bc1638492e16.png)

Problem is fixed as soon as I disable **works everywhere** of [PhotoShow](https://github.com/Mr-VincentW/PhotoShow). It used to work some weeks ago.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This should have been fixed with update 4.21.0. Please wait for it to get reviewed by browser app stores and try again later.
