### ISSUE TITLE
开启浮图秀会导致Steam商店页面功能有问题

### ISSUE THREAD

**Issue by Kuroki79** [Mr-VincentW/PhotoShow#108]
开启浮图秀后，在Steam促销页面所有的游戏板块都无法互动。
![msedge_iD61zP9uBC 00_00_00-00_00_30 00_00_00-00_00_05](https://user-images.githubusercontent.com/17521925/224591008-84017f82-6e6a-4f56-81d4-3c307a3410a7.gif)

**Comment by Mr-VincentW** [comment]
感谢反馈。请更新至 4.21.0 后查看问题是否继续。如果您使用的是 Edge 浏览器，该版本目前仍在审核中。

**Comment by Kuroki79** [comment]
我用的是edge浏览器，那我等更新推送了再试试

**Comment by Mr-VincentW** [comment]
您可以附上页面链接，以便我测试，谢谢。

**Comment by Kuroki79** [comment]
https://store.steampowered.com/publisher/capcom/sale/CapcomPubSale

**Comment by Mr-VincentW** [comment]
是的，此问题会在您更新至 4.21 后得到修复。

**Comment by Kuroki79** [comment]
OK，感谢解答
