### ISSUE TITLE
下载图片没有格式后缀

### ISSUE THREAD

**Issue by penghusile** [Mr-VincentW/PhotoShow#11]
我用这款插件下载知乎的图片有时候不带格式后缀（如.jpg），请问是什么原因呢

**Comment by Mr-VincentW** [comment]
您好，感谢反馈。
通常出现这种情况是因为图片的原始链接中就不包含文件后缀名，多数情况下这并不影响图片在浏览器内展示，但浮图秀无法猜测出图片的真实编码格式。
您可以附上相关链接，方便我具体排查，谢谢。
