### ISSUE TITLE
插件更新后pixiv最近保存图片失败,edge浏览器扩展   版本 111.0.1661.41 (正式版本) (64 位)

### ISSUE THREAD

**Issue by Avalon913** [Mr-VincentW/PhotoShow#110]
![image](https://user-images.githubusercontent.com/90371683/225933719-46b20064-d2bd-47b2-9707-25d003fd9fb5.png)
![image](https://user-images.githubusercontent.com/90371683/225933934-40d06fbb-31b7-4be7-8ea7-812270642bb4.png)

这几天直接按s保存都是显示保存失败,想问下作者是什么情况,就算不这样设置都不能保存成功,其他网站正常

**Comment by Mr-VincentW** [comment]
感谢反馈，已于更新 4.22 中修复此问题，敬请等待各浏览器应用商店过审后上架。
