### ISSUE TITLE
感谢，能否增加针对弹出图片的更多操作功能

### ISSUE THREAD

**Issue by minshifu** [Mr-VincentW/PhotoShow#111]
**感谢制作这个非常棒的，非常有用的扩展。请问能否为弹出的图片增加更多的操作可能。比如，允许鼠标拖动弹出的图片到新标签页，以便进行图片下载等其他可能的操作；或者允许弹出图片保持弹出状态，然后可以在图片上点击右键，然后对弹出图片进行更多操作？多谢哈！**

**Comment by Mr-VincentW** [comment]
感谢反馈，在浮图秀展示大图时，您可以通过 `Tab` 键在新浏览器标签中打开大图，也可以通过 `S` 键下载大图。更多操作您可以查看浮图秀设置面板（点击浏览器地址栏旁浮图秀的插件图标）。

**Comment by minshifu** [comment]
> 感谢反馈，在浮图秀展示大图时，您可以通过 `Tab` 键在新浏览器标签中打开大图，也可以通过 `S` 键下载大图。更多操作您可以查看浮图秀设置面板（点击浏览器地址栏旁浮图秀的插件图标）。

好的，十分感谢！
