### ISSUE TITLE
请问这个插件怎么实现的复制图像到剪贴板，。感觉好方便啊。

### ISSUE THREAD

**Issue by yangchen158158** [Mr-VincentW/PhotoShow#112]
https://chrome.crxsoso.com/webstore/detail/hover-zoom+/pccckmaobkjjboncdfnnofkonhgpceea
请问这个插件怎么实现的。感觉好方便啊。
复制图像到剪贴板，
按下此键时，图像被复制到剪贴板。

**Comment by yangchen158158** [comment]
作者可以添加上吗？

**Comment by Mr-VincentW** [comment]
感谢反馈。出于安全考虑，浏览器并不允许插件向系统剪贴板内复制图片。目前有变通的方法但不尽完美（会丢失透明通道信息）。浮图秀未来可能会尝试此方案但目前还比较谨慎。BTW，我个人测试 Hover-Zoom+ Chrome 官方应用市场的版本，该复制功能并不工作。
我将关闭此 issue 因其与 #38 重复。谢谢。

**Comment by Mr-VincentW** [comment]
复制图片的功能已于更新 4.49 中实现，请参阅此前引述的 #38 。谢谢！
