### ISSUE TITLE
开启和关闭的快捷键不起作用

### ISSUE THREAD

**Issue by i110077** [Mr-VincentW/PhotoShow#116]
测试环境:Win10 Firefox 111.0.1
新加的开启关闭快捷键不起作用啊, 无论设置哪个键都没有任何反应哦, 期待修复一下, 辛苦了

**Comment by Mr-VincentW** [comment]
感谢反馈，这是 Firefox 插件系统的一个功能缺失造成的，浮图秀将在下次更新时尝试修复。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.22.1 中修复，敬请期待各浏览器应用市场完成审核后上架，谢谢。
