### ISSUE TITLE
部分网站看大图和S键保存的功能失效

### ISSUE THREAD

**Issue by Yona10777** [Mr-VincentW/PhotoShow#117]
版本 chrome 110.0.5481.178

pinterest正常 但是关联的一些家具网站、设计网站等，目前不像旧版本支持看大图和S键保存大图了。
例如：

https://www.paintingforhome.com/blogs/crafts-ideas/modern-living-room-rug-ideas-extra-large-modern-rugs-for-office

https://www.homethreads.com/products/rugs/modern/contempo-cpo-3843?sku=CPO3843-27710

**Comment by Mr-VincentW** [comment]
感谢反馈。经测试，所有未被浮图秀专门适配的网站上，图片下载功能均失效，此问题将在下次更新中修复。不过看大图功能并未受到影响，如果您依然不能看大图，欢迎进一步补充说明。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.22.1 中修复，敬请期待各浏览器应用市场完成审核后上架，谢谢。
