### ISSUE TITLE
PhotoShow pre-load images on hover, can it to turn off?

### ISSUE THREAD

**Issue by HentaiRyuu** [Mr-VincentW/PhotoShow#12]
Edit: I know this is pre-load thing on hover. 
but if my internet or server is slow it will made thing go worst.

ex. when I try to move my mouse to something i want it to show, it will just load everything that I move mouse pass it.
I think it's better to have option to turn this off or something.

![photoshowbug](https://user-images.githubusercontent.com/26791163/100857482-11b74f00-34d0-11eb-97af-0b534d85ae24.png)

**Comment by Mr-VincentW** [comment]
Thank you for your feedback.

Actually, the current version of PhotoShow doesn't preload any pics, though this feature is in the plan. Definitely, a toggle will be offered too then.

The 404 error log you saw in the console is not from images **"preloading"** but **detection**. On some certain websites (such as _pixiv_), PhotoShow will detect the largest pic it knows and fallback to loading an alternative one if the first attempt fails. The failure brings you the error message and unfortunately, as far as I know, there's no way to prevent this browser logging behavior.

And, PhotoShow doesn't **"load everything"** that your mouse moves through. It only loads the image when your mouse has been hovering on a thumbnail for over 200ms. This balances between proper network using and an instant enough loading action when the user actually wanna see the HD images.

Anyway, good ideas are always welcome. Thank you.

**Comment by Mr-VincentW** [comment]
However, I just realized that the detection will also happen even when you're not triggering your activation key. This can be a tough issue as fixing this will potentially affect the whole working flow. I will leave this problem to the future refactoring and keep this issue open until then.
