### ISSUE TITLE
建议网站开关做成白名单模式

### ISSUE THREAD

**Issue by CoBear97** [Mr-VincentW/PhotoShow#121]
个人目前体验只需要一两个网站需要这种功能，但是我的是未知网站，所以其他网站不需要插件的时候还得主动开关关闭掉

**Comment by Mr-VincentW** [comment]
已于更新 4.24 起支持白名单模式，可从浮图秀配置面板中启用。
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/f8a800cd-ed0d-4034-b94f-e4e22690fd26)

**Comment by CoBear97** [comment]
太棒了！感谢🙏🏻

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Vincent W. ***@***.***&gt;
发送时间: 2023年5月21日 18:00
收件人: Mr-VincentW/PhotoShow ***@***.***&gt;
抄送: CoBear97 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Mr-VincentW/PhotoShow] 建议网站开关做成白名单模式 (Issue #121)





 
已于更新 4.24 起支持白名单模式。您可从浮图秀配置面板中启用。
