### ISSUE TITLE
delay in pinterest

### ISSUE THREAD

**Issue by davidp88** [Mr-VincentW/PhotoShow#126]
Manytimes before showing the photo on hover there is a slight delay of 3-4 secs in pinterest

latest ff beta,win10 64b

**Comment by Mr-VincentW** [comment]
Thanks for your feedback.

Unfortunately, I wasn't able to reproduce the issue you mentioned on Pinterest. However, please check the following PhotoShow settings to see if it has accidentally got an extra long "**activation delay**" time.
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/b63fd443-b6c1-4017-96b4-e119f80a7482)

Also, PhotoShow only displays HD images after they have been loaded, which might take some time when your connection is poor.

**Comment by davidp88** [comment]
Mine is a high speed internet connection of 50mbps,I've seen that setting,pls test thoroughly at here -- [https://in.pinterest.com/pin/56717276548957728/](url)

**Comment by Mr-VincentW** [comment]
I tested the provided link, still not being able to see any unexpected delay.

**Comment by davidp88** [comment]
As in the gif even after 4 secs there is no photo being displayed on hover

![ps](https://github.com/Mr-VincentW/PhotoShow/assets/80623401/fa40de71-84fd-4a0c-9467-1e7bc134e4d4)

**Comment by Mr-VincentW** [comment]
Were you visiting the page without logging in?

**Comment by davidp88** [comment]
no,I'm signed in

**Comment by Mr-VincentW** [comment]
This looked weird, it works fine on my FF 114.0.1 (64-bit).
![PhotoShow Screenshot](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/7c1e9aef-049b-49c4-8167-ce0129988aeb)
