### ISSUE TITLE
Don't expand images that are used for animations

### ISSUE THREAD

**Issue by alejandro5042** [Mr-VincentW/PhotoShow#127]
Microsoft Teams uses images to animate emojis. Typically, it only shows one...

![image](https://github.com/Mr-VincentW/PhotoShow/assets/3143819/c4a7d200-f74f-44fc-a247-c36ae8980aa1)

But PhotoShow wants to show the entire animation strip image:

![image](https://github.com/Mr-VincentW/PhotoShow/assets/3143819/5f8de8cf-f113-453b-9a8e-591935d05919)

Could PhotoShow detect that the display is only a portion of the entire image, and then ignore those images?

**Comment by Mr-VincentW** [comment]
Thanks for the feedback, I'll look into this case later.

**Comment by Mr-VincentW** [comment]
This issue has been fixed with update 4.29. Cheers.
