### ISSUE TITLE
拖拽图片下载功能优化

### ISSUE THREAD

**Issue by Gally-Youko** [Mr-VincentW/PhotoShow#132]
https://twitter.com/Edgar_Syu/status/1704436281235931385/photo/1
浏览上面这条推特时发现，直接按s下载或者按tab新页面打开后再下载会下载1519X2048的图，而右键另存为或者拖拽到新标签页中打开图片或者右键新标签页中打开图片，都是更大的2225X3000的图。能不能让浮图秀实现拖拽下载更大的图？例如上面这个例子中不在新标签页中打开图片也能直接拖拽下载更大的2225X3000的图。

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题应已修复。
