### ISSUE TITLE
On YouTube video pages thumbnails now block the whole view

### ISSUE THREAD

**Issue by thesla13** [Mr-VincentW/PhotoShow#133]
Hello, Mr. Vincent.
Thank you so much for your wonderful extension! There are very few others that make browsing experience as much better as yours does.

However, since a couple of days ago a bug of sorts has come up. The thing is I also use an extension called [Tweaks for YouTube](https://chromewebstore.google.com/detail/tweaks-for-youtube/ogkoifddpkoabehfemkolflcjhklmkge). About a week ago there was a bug: when the extension was set to open YT videos in a paused state, instead of displaying a given video's thumbnail it would only display a black screen. Since then I've contacted the extension's developer, he confirmed
 that, indeed, YouTube people have tweaked some APIs, he's working on it, and now he's updated his extension, and the problem is — now PhotoShow puts a video's thumbnail on top of the video, whether paused or being played back.

I'm frankly at miss as to whose problem is this. I've already sent a message to the developer of TfYT, but thought that maybe you should know too.

![Snipaste_2023-11-23_15-05-24](https://github.com/Mr-VincentW/PhotoShow/assets/55979516/76d78476-8568-4e3a-bc6c-385b32cdd890)

**Comment by Mr-VincentW** [comment]
Hi, thank you for your feedback.

Unfortunately, I wasn't able to replicate this issue, PhotoShow didn't display an HD image for me on this video. I assume it might have something to do with my settings for **Tweaks for YouTube**. So please try to
- Guide me on how to set up **Tweaks for YouTube** to replicate this problem OR
- You can tick this PhotoShow settings as per the screenshot below to disable HD image display when the source image is large enough. Please kindly note that this setting works for all sites.
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/581e651c-4ce3-47bc-98a2-a3b8d2cf4960)

**Comment by thesla13** [comment]
@Mr-VincentW Hey, thanks for your reply!

The problem has been fixed for a few days now. I've contacted the developer of Tweaks for YouTube, he has made adjustments, and, since version 3.59.1, thumbnail preview overlaying video is no longer an issue.

Yet again, thank you for your work!
