### ISSUE TITLE
右键保存不了图片

### ISSUE THREAD

**Issue by xivi1839** [Mr-VincentW/PhotoShow#137]
右键保存不了图片

https://www.imdb.com/title/tt13392064/mediaviewer/rm2439924481?ref_=ttmi_mi_all_pos_46

**Comment by Mr-VincentW** [comment]
感谢反馈，由于该网站的技术实现原因，此问题没有快速的解决方案。我将保留此 issue 直至浮图秀未来较大更新中解决。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.45 中得到解决。请等待浏览器应用市场完成审核后上架。谢谢。
