### ISSUE TITLE
Feature Request: Add DuckDuckGo Images

### ISSUE THREAD

**Issue by vertigo220** [Mr-VincentW/PhotoShow#14]
Works on Google, but not DDG, or Bing, but don't really care about that, just mentioned it because that's what DDG uses.

**Comment by Mr-VincentW** [comment]
Thank you for the request. Currently, PhotoShow works on Bing bug not on DDG. I'm gonna give it a go with fitting DDG recently.

**Comment by vertigo220** [comment]
Strange. It didn't seem to work on Bing when I tested it before posting, but it is now. Look forward to it working on DDG!

**Comment by Mr-VincentW** [comment]
PhotoShow has started supporting DuckDuckGo since version 4.6.2.0. Thanks.
