### ISSUE TITLE
How don't preview small images like: budy icon /avatar, Interface images like caret etc

### ISSUE THREAD

**Issue by decembre** [Mr-VincentW/PhotoShow#140]
I use Flickr and PhotoShow preview the avatar of user, some elements of its interface etc...

And i notice the same for some addon.
By example with:
<a href="https://addons.mozilla.org/fr/firefox/addon/simple-translate/">Simple Translate</a>
When i select a text to translate, its icon appear near it.
If i hover it, your addon preview a big icon.

**Comment by Mr-VincentW** [comment]
PhotoShow has stopped parsing images from browser extensions since update 4.32.0.
Thanks for your feedback.

**Comment by decembre** [comment]
Woha, very fast update:
thanks, work like a charm... for the addon.

But for Flickr ?
