### ISSUE TITLE
疑问：微博图片无水印和大图是否能兼得

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#145]
我看到[网上有方法](https://5ime.cn/images-spider.html)可以将微博图片改成无水印，但我实验了下，发现按照这个方法弄出的无水印图片会比原图尺寸小。
比如[此微博](https://weibo.com/2877484941/O74obkHs1)的图三，原图地址为[https://wx1.sinaimg.cn/original/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg](https://wx1.sinaimg.cn/original/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg)或[https://wx1.sinaimg.cn/mw2000/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg](https://wx1.sinaimg.cn/mw2000/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg)，为1350px宽，无水印图片地址为[https://wx1.sinaimg.cn/oslarge/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg](https://wx1.sinaimg.cn/oslarge/ab82ef8dgy1ho6ikibo4rj211i1hcqm7.jpg)，为690px宽。不知道是否有办法能够获取到无水印的大图，如果能的话可以集成到浮图秀的规则中。

**Comment by Mr-VincentW** [comment]
感谢反馈。
浮图秀目前也没有可以获取最大无水印图片的地址解析规则。如果将来有新的发现，会持续更新集成。
