### ISSUE TITLE
[增加网站支持]蜜柑计划原图

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#146]
### 官网
- 国际版官网（大陆无法访问）：[https://mikanani.me/](https://mikanani.me/)
- 国内版官网（仅限大陆访问）：[https://mikanime.tv/](https://mikanime.tv/)

### 规则
去掉图片网址.jpg后所有的参数

### 示例
- 小图（400px宽）：[https://mikanani.me/images/Bangumi/202402/156c8321.jpg?width=400&height=400&format=webp](https://mikanani.me/images/Bangumi/202402/156c8321.jpg?width=400&height=400&format=webp)
- 原图（大图，1519px宽）：[https://mikanani.me/images/Bangumi/202402/156c8321.jpg](https://mikanani.me/images/Bangumi/202402/156c8321.jpg)

**Comment by Mr-VincentW** [comment]
感谢反馈及详尽的规则描述。浮图秀已在更新 4.34 中添加对 Mikan 的支持。
