### ISSUE TITLE
[增加网站支持]Bangumi番组计划

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#147]
### 官网
- [https://bgm.tv/](https://bgm.tv/)
- [https://bangumi.tv/](https://bangumi.tv/)
- [https://chii.in/](https://chii.in/)
三者是完全等同的，可以视作彼此同步的镜像。但三者的网站图片的地址（图床）全在bgm.tv

#### 规则一（对应示例一）
将https://lain.bgm.tv/(%1/)pic/cover/%2/%3.jpg
换成https://lain.bgm.tv/pic/cover/l/%3.jpg
其中，英文括号代表可能包含可能不包含，%1、%2、%3分别代表在此位置不同的字符，下同

#### 规则二（对应示例二）
将https://lain.bgm.tv/pic/user/l/%1.jpg?%2
换成https://lain.bgm.tv/pic/user/c/%1.jpg

#### 示例一
- 小图一：[https://lain.bgm.tv/pic/cover/c/c6/69/441084_tco08.jpg](https://lain.bgm.tv/pic/cover/c/c6/69/441084_tco08.jpg)（来自[搜索结果第一条](https://bgm.tv/subject_search/%E5%B0%8F%E9%85%92%E9%A6%86)封面）
- 小图二：[https://lain.bgm.tv/r/400/pic/cover/l/c6/69/441084_tco08.jpg](https://lain.bgm.tv/r/400/pic/cover/l/c6/69/441084_tco08.jpg)（来自[某番主页面](https://bgm.tv/subject/441084)）
- 原图（大图）：https://lain.bgm.tv/pic/cover/l/c6/69/441084_tco08.jpg

#### 示例二
- 小图（120px宽）：[https://lain.bgm.tv/pic/user/l/000/80/04/800445.jpg?r=1701944239&hd=1](https://lain.bgm.tv/pic/user/l/000/80/04/800445.jpg?r=1701944239&hd=1)（来自[某日志](https://bgm.tv/blog/330530)）
- 原图（512px宽）：[https://lain.bgm.tv/pic/user/c/000/80/04/800445.jpg](https://lain.bgm.tv/pic/user/c/000/80/04/800445.jpg)（来自[某用户主页](https://bgm.tv/user/800445)）

### 碎碎念
- 由于没有提供模板，规定在申请规则时内容和正文要怎么写，所以这个体例是我自以为合适的，要是哪有不当或未尽之处敬请指出
- 在[文档](https://github.com/Mr-VincentW/PhotoShow/blob/archive/docs/README_zh-CN.md#%E6%94%AF%E6%8C%81%E7%BD%91%E7%AB%99)中说「如果上述列表中不包含您所钟爱的网站，欢迎[向作者反馈](https://github.com/Mr-VincentW/PhotoShow/blob/archive/docs/README_zh-CN.md#%E8%81%94%E7%B3%BB%E4%BD%9C%E8%80%85)以获取更多支持。」而这里指向一个邮箱。不过由于我觉得可能Issue是一个更适合的反馈渠道，于是自作主张（可能是自作聪明）地在Issue区提出，要是作者更希望用邮箱等其他方式反馈，烦请告知。

**Comment by Mr-VincentW** [comment]
感谢反馈及详尽的规则描述。浮图秀已在更新 4.34 中添加对 Bangumi 的支持。
