### ISSUE TITLE
小红书没有展示出最大尺寸照片

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#150]
以[这篇笔记 ](https://www.xiaohongshu.com/explore/66129a07000000001b00867c) 为例，扩展解析到的图片地址为``` http://sns-webpic-qc.xhscdn.com/202404151120/ed03006ce86129d110f17fd94eccc4dd/1040g2sg3119rhghjmi0g48krtrv2k59s9b5d5co!nd_dft_wlteh_webp_3 ```，是 1080px 宽的，但实际上有 1420px 宽，地址为：
``` https://sns-img-al.xhscdn.com/1040g2sg3119rhghjmi0g48krtrv2k59s9b5d5co?imageView2/2/w/format/png ``` （png 格式）
``` https://sns-webpic.xhscdn.com/1040g2sg3119rhghjmi0g48krtrv2k59s9b5d5co?imageView2/2/w/0/format/jpg/v3 ``` （jpg 格式）
还有一些在线解析器解析到的地址是``` https://sns-img-bd.xhscdn.com/1040g2sg3119rhghjmi0g48krtrv2k59s9b5d5co ```但在我这打不开，可能是防盗链之类，我不会开发不懂了，供你参考。
这上面有 png 和 jpg 两种格式，我不清楚哪个才是原图

另外，有网友在[他的文章 ](https://zhuanlan.zhihu.com/p/638489266) 中分享了无水印源码，不知道能不能有所启发或帮助

还是以这篇笔记为例，在[搜索页面 ](https://www.xiaohongshu.com/search_result?keyword = %25E5%2590%25B9%25E5%2590%25B9%25E9%25A3%258E%2520%25E6%2595%25A3%25E6%2595%25A3%25E7%258F%25AD%25E5%2591%25B3&source = unknown) 和[作者页面 ](https://www.xiaohongshu.com/user/profile/57ab3e2a5e87e712a4f8153c) 都只展示了 640px 宽的图：
![image](https://github.com/Mr-VincentW/PhotoShow/assets/67213568/5d49611e-5a1b-4e40-99dc-3d27ece863fd)
![image](https://github.com/Mr-VincentW/PhotoShow/assets/67213568/a2ac355f-d1da-4dc6-ba82-096a41f3bb73)
其解析到的地址是``` http://sns-webpic-qc.xhscdn.com/202404151149/d10f5f8e5fa7e4480deb500bbb97699c/1040g2sg3119rhghjmi0g48krtrv2k59s9b5d5co!nc_n_webp_mw_1 ```

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题将在更新 4.37 中修复。
