### ISSUE TITLE
无法获取img属性完整URL地址

### ISSUE THREAD

**Issue by AirSkye** [Mr-VincentW/PhotoShow#151]
https://unam4.github.io/2024/03/01/apache-cayenne%E4%BB%A3%E7%A0%81%E5%AE%A1%E8%AE%A1/
该博客文章中插件获取的图片URL地址为：https://unam4.github.io/image-20240301125126266.png
![image](https://github.com/Mr-VincentW/PhotoShow/assets/55659004/89a992bc-3471-4aa0-8864-41ba5b9721e9)

而实际的图片文件地址为：https://unam4.github.io/2024/03/01/apache-cayenne%E4%BB%A3%E7%A0%81%E5%AE%A1%E8%AE%A1/image-20240301125126266.png
![image](https://github.com/Mr-VincentW/PhotoShow/assets/55659004/718f6556-4271-4ca1-aac0-1c952007ff48)

导致图片无法显示

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题将在更新 4.37 中修复。
