### ISSUE TITLE
[规则申请] QQ音乐封面大图

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#152]
### 示例
以[该专辑 ](https://y.qq.com/n/ryqq/albumDetail/000JCMmU28epib) 为例，解析到的专辑地址是``` https://y.qq.com/music/photo_new/T002R300x300M000000JCMmU28epib_2.jpg?max_age = 2592000 ```，但这张图只有 300px宽，而实际上是有 800px宽的图的``` https://y.qq.com/music/photo_new/T002R800x800M000000JCMmU28epib.jpg ```

### 规则总结
假设专辑地址为``` https://y.qq.com/n/ryqq/albumDetail/%1 ```（其中 「%1」 能唯一确定一张专辑，姑且称之为「专辑 ID」）
则专辑大图地址为``` https://y.qq.com/music/photo_new/T002R800x800M000%1(_%2).jpg(max_age = %2) ```，其中，括号及内部包含的代表可有可无 ，%2 为任意自然数 ，%2 为任意字符串（可以为空）
这样，就能得到一张 800px宽的专辑图片

### 其他
能够发现，专辑尺寸写在``` T002R ```和专辑 ID 之间，通过替换 800 为 150、500 等得到相应宽的图像。可惜的是，我测试了 900 × 900 到 3000 × 3000 中所有的整百组合，没有找到比 800 × 800 更大的选项。不知道是否有比 800 × 800 更大的专辑封面图片（网易云都上到了 2500 × 2500，QQ 音乐的 800 × 800 确实有点不够清晰）

**Comment by Mr-VincentW** [comment]
感谢反馈，将从更新 4.37 起适配QQ音乐。
