### ISSUE TITLE
抖店后台大图功能新版本失效

### ISSUE THREAD

**Issue by Leslie90s** [Mr-VincentW/PhotoShow#154]
fxg.jinritemai.com，compass.jinritemai.com，buyin.jinritemai.com等抖店后台网页内无法显示大图，大概是4.3x之后的版本失效，找到4.28旧版本是正常的，但总会自动更新，或者有什么方法可以关闭自动更新

**Comment by Mr-VincentW** [comment]
感谢反馈。就我所知目前无法禁止浏览器自动更新所安装的插件。
由于我没有抖店账号，无法登录查看具体的问题，故无能解决此问题。我将关闭此 issue，如果您能提供一个临时账号供调试，请重开之。谢谢。
