### ISSUE TITLE
油管短视频部分功能无法进行交互

### ISSUE THREAD

**Issue by soeyu** [Mr-VincentW/PhotoShow#155]
版本 4.35.0
启用拓展功能后，动态添加的style，导致了视频内单击暂停播放、右侧评论区各功能按钮都不能进行交互
firefox 124,Chrome 123 均能复现
https://www.youtube.com/shorts/Viv0Mf-ZCMs

https://github.com/Mr-VincentW/PhotoShow/assets/3954659/c1ec5855-b4c3-48bb-8c0f-424eb8b5a032

**Comment by Xeroxeon** [comment]
首页的视频也无法获取封面，只有在作者频道才能获取

**Comment by Mr-VincentW** [comment]
感谢反馈，此二问题将在更新 4.37 中修复。
