### ISSUE TITLE
Update 4.37 stopped working on aliexpress.ru

### ISSUE THREAD

**Issue by ipwin-github** [Mr-VincentW/PhotoShow#157]
Thanks for the great browser extension. Problem. After updating to version 4.37 on the website https://aliexpress.ru/ photos in user reviews are now displayed only in thumbnail mode. Up to 4.37 photos in user reviews are displayed in their original size.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This issue has been addressed in update 4.39.
