### ISSUE TITLE
PhotoShow icon does not appear in the context menu.

### ISSUE THREAD

**Issue by masked-shizuma** [Mr-VincentW/PhotoShow#158]
Hello,
I am using PhotoShow 4.40.0 on Firefox 128.0.3. PhotoShow icon does not appear in the context menu.
Please check.
Thank you.

**Comment by Mr-VincentW** [comment]
Hey, thank your for letting me know. 
Please attach more details, maybe the site you were on and whether you're on Windows or Mac.
It worked well for me when I was testing it myself on Google Images as per the screenshot below.
![image](https://github.com/user-attachments/assets/ac79dd69-9084-4618-89ea-d12f584ff2c5)

**Comment by masked-shizuma** [comment]
Thank you for your response. I am using Windows 10.
I disabled all extensions except PhotoShow and tried again, but the result did not change.
It might be because I am using custom user.js and .css files, which could be affecting it.
Testing these one by one is difficult, so I will give up.
Thank you.

**Comment by Mr-VincentW** [comment]
If PhotoShow is able to show HD images for you, it is unlikely that custom JS or CSS would affect its context menu items.
Please kindly check if this settings has been accidentally turned off for PhotoShow -
![image](https://github.com/user-attachments/assets/4a648c41-d0f4-4180-99f8-6c7d8edd9eec)

**Comment by masked-shizuma** [comment]
Thank you for your response.
The PhotoShow icon appeared in the context menu.
I followed your advice and checked the context menu items.
Although the setting was originally on, I turned it off and then back on, which made the icon appear.
Thank you.
