### ISSUE TITLE
小云的浮图功能现在无法使用了

### ISSUE THREAD

**Issue by dingding1024** [Mr-VincentW/PhotoShow#159]
8月7日测试，网易云的浮图无法使用了，都无法识别

**Comment by Mr-VincentW** [comment]
感谢反馈。
应 Chrome 应用市场技术升级要求，浮图秀近期完成了一次较大更新。对网易云音乐的支持因其网站的结构问题暂时停止，相关修复预计会在近期完成。敬请期待。

**Comment by Mr-VincentW** [comment]
浮图秀已于更新 4.44.0（发布于 2024-09-10）修复了对网易云音乐的支持。敬请期待各浏览器应用市场完成审核后上架。
（PS：在 Firefox 下对该网站可能依然支持不良，概系 Firefox 自身原因所致，决定暂不予处理。）
