### ISSUE TITLE
浮图增加放大缩小翻转下载负载等图标

### ISSUE THREAD

**Issue by yanghe1117** [Mr-VincentW/PhotoShow#16]
能否在展示的浮图上增加放大缩小翻转下载负载等图标，而不用键盘的快捷键，建议，3q

**Comment by Mr-VincentW** [comment]
感谢反馈。浮图秀未来可能会增加一种“增强”模式，预期会在一个稳定不会自动消失的弹层中展示大图并提供旋转、下载等操作的交互按钮。但目前浮图秀的交互模式旨在提供一个轻量快捷的“鼠标移过/移出”体验，所以无法添加更“重”的交互。敬请期待未来版本。
