### ISSUE TITLE
请问为什么不支持pixiv这个网站

### ISSUE THREAD

**Issue by LuvEven** [Mr-VincentW/PhotoShow#161]
https://www.pixiv.net/ranking.php?mode=daily&date=20240810，没有获取成功，有办法获取这个超链接的图片吗？
![image](https://github.com/user-attachments/assets/a56b7d7e-dd1c-47b1-962c-f91aa54b54b4)

**Comment by Mr-VincentW** [comment]
感谢反馈。
浮图秀从 4.0.3 版本（发布于2019年11月23日）起即支持该网站。请对照如下步骤排查问题：
- 确保您所使用的是最新版本浮图秀。
- 请在浮图秀设置面板中查看是否意外对 pixiv 关闭了浮图秀（图示1）。
- 是否启用了白名单模式但未对 pixiv 豁免（图示2）.
![image](https://github.com/user-attachments/assets/510312cf-6270-4742-82a1-70bee1ca0f4d)

如果问题依旧，欢迎继续跟进此 issue 并附上更详细的信息。包括您的浏览器及其版本、浮图秀版本、出问题的页面链接等；如有必要，相应的屏幕截图及操作描述将更加有助于问题排查。谢谢。

**Comment by Mr-VincentW** [comment]
浮图秀已更新至 4.41，此问题应当已得到修复。敬请期待各浏览器应用市场完成审核并上架。
