### ISSUE TITLE
希望增加对B站评论区笔记图片的支持

### ISSUE THREAD

**Issue by a3087814532** [Mr-VincentW/PhotoShow#162]
希望增加对B站评论区笔记图片的支持
![e4009fd1-2e2c-436a-918a-30859fcf9c63](https://github.com/user-attachments/assets/ed29f06e-5e21-495e-b162-d1f341251ab9)

**Comment by Mr-VincentW** [comment]
感谢反馈。
因技术原因，对 bilibili 评论区的支持比较复杂，预计将留待未来较大版本更新时尝试解决。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.45 中得到解决。请等待浏览器应用市场完成审核后上架。谢谢。
