### ISSUE TITLE
希望增强对于淘宝和京东站的支持

### ISSUE THREAD

**Issue by minshifu** [Mr-VincentW/PhotoShow#163]
你好，很喜欢这款扩展，一直在用。但是目前对于淘宝和京东网页不支持。如下图，使用咱们的扩展只能跳出显示小图，但是使用另外某款扩展当鼠标悬停在小图上后就会跳出显示原始大图。而在京东的类似网页上则是连小图都不会跳出。希望可以改进增强支持，多谢了！

![图片](https://github.com/user-attachments/assets/5984e77e-752a-4cb2-9945-dcba79a603eb)

![图片](https://github.com/user-attachments/assets/92c80d89-756f-4ac7-8d35-8fa3bd3a14c7)

**Comment by Mr-VincentW** [comment]
感谢反馈。我个人测试未能发现此问题。请参考如下步骤排查原因：
- 确保您的浮图秀是最新版本（当前为 4.41）。
- 如果问题依旧，请提供更详细的信息比如出问题的页面链接、您的浏览器名称及其版本等。您还可以在出问题的页面点击浮图秀设置面板，通过上面的“邮件”链接发送邮件给我，则所需详细信息会自动携带，如下图所示：
![image](https://github.com/user-attachments/assets/afa96fdd-d601-4b47-a2cc-32e30c081cc6)

**Comment by minshifu** [comment]
> 感谢反馈。我个人测试未能发现此问题。请参考如下步骤排查原因：
> 
>     * 确保您的浮图秀是最新版本（当前为 4.41）。
> 
>     * 如果问题依旧，请提供更详细的信息比如出问题的页面链接、您的浏览器名称及其版本等。您还可以在出问题的页面点击浮图秀设置面板，通过上面的“邮件”链接发送邮件给我，则所需详细信息会自动携带，如下图所示：
>       ![image](https://private-user-images.githubusercontent.com/54405631/361325377-afa96fdd-d601-4b47-a2cc-32e30c081cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDgyNTksIm5iZiI6MTcyNDg0Nzk1OSwicGF0aCI6Ii81NDQwNTYzMS8zNjEzMjUzNzctYWZhOTZmZGQtZDYwMS00YjQ3LWEyY2MtMzJlMzBjMDgxY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEyMjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDgyZTEyOWFkODljODUzYWYzNTUyMjcxZjEwNDk1YjY5M2JiZjcwNGUwNjFhOWM1NzE0Nzk0MTFjMTE4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fg5JWVVO1WoK3kiCznNlOlYIJPe5_FRua8_2PWke44)

好的多谢

**Comment by Mr-VincentW** [comment]
如邮件沟通，Firefox 对浏览器插件的管理似有问题，很多时候需要重新安装相关插件甚至 Firefox 本身才能使其正常工作，不妨尝试。
