### ISSUE TITLE
新浪微博图片为小图

### ISSUE THREAD

**Issue by soeyu** [Mr-VincentW/PhotoShow#164]
![1](https://github.com/user-attachments/assets/45e4ec28-2349-4a6e-815b-142a1eceb97e)

悬浮的图片地址还是小图的地址

**Comment by Mr-VincentW** [comment]
感谢反馈。请附上具体页面的链接以便问题排查。
您可以在访问出问题的页面时，通过浮图秀设置面板上的邮件图标发送邮件，则调试所需信息将自动添加到邮件内容中。如果下图所示：
![image](https://github.com/user-attachments/assets/ac14247b-76d7-4607-9892-830196001f32)

**Comment by Mr-VincentW** [comment]
Firefox 对浏览器插件的管理似有问题，很多时候需要重新安装相关插件甚至 Firefox 本身才能使其正常工作，不妨尝试。

**Comment by soeyu** [comment]
拓展移除重装后恢复
