### ISSUE TITLE
Image zoom is same size as original image, or no zoom at all

### ISSUE THREAD

**Issue by nollinvoyd** [Mr-VincentW/PhotoShow#165]
PhotoShow 4.44.1, Windows 10

This has been happening for a while. I only tested lately with Google Images for examples.  Different image searches all have the same symptoms.  

Example:  [https://www.google.com/search?newwindow=1&client=firefox-b-1-d&sca_esv=673b5efe1873ee37&sca_upv=1&sxsrf=ADLYWIL2UFGOWwl2nZujte_278mNr94_vA:1724874435771&q=yankees&udm=2&fbs=AEQNm0Aa4sjWe7Rqy32pFwRj0UkWtG_mNb-HwafvV8cKK_h1a5eSkyfXNgRC6a9SKsMT7FKel2oEVH7CAeL9GJLZ9zSE1b0VTwOacLkI4XgtHWeWNmKPMmJVT-fsL2j8HgVBOedFE0rcv3l9ce7iX7VQHiBT41qOitP2uFNPJwqo3Nj1J21-Gh5tg3bNyqf1kLEJ7mR0Orp4LTigYJIGRfW985SFZs7PWg&sa=X&ved=2ahUKEwjO3pqAupiIAxVcEEQIHcvqExsQtKgLegQIExAB&biw=1216&bih=550&dpr=1.58](url)

**Comment by nollinvoyd** [comment]
Tested in Chrome.  No problems.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback.
PhotoShow 4.41 did have an issue for Google Images on Firefox and it has been fixed in update 4.42. Please try it again.
Please note that sometimes you might need to reinstall extensions or even Firefox itself to make updated extensions work properly.

**Comment by nollinvoyd** [comment]
Thanks for taking care of it.

**Comment by nollinvoyd** [comment]
What I'm experiencing now is the zoom factor for all images  is just slightly greater than the original image.  

Is that the intention?  If I recall correctly, is was far greater in the past.

If the original image was fully displayed with it's actual border dimensions, the minimal difference in size would be more apparent

![ohoto](https://github.com/user-attachments/assets/d885c2d9-ad6b-4b24-9441-d35ae3c365a1)

![photo2](https://github.com/user-attachments/assets/50d97706-1433-42e9-b2e0-c2ce790d9834)

**Comment by Mr-VincentW** [comment]
Apologies for the issues you've been stuggling with. Another defect of PhotoShow which may cause this problem has been identified and fixed in update 4.43. Hopefully, this fix will bring the good old times back 😅.

Feel free to let me know again if it doesn't work for you. Cheers.

**Comment by tyro-xc** [comment]
有些时候图片太小了 鼠标悬浮上去后放大的图片也太小了 能不能加一个if判断 如果图片的分辨率小于某一个数值 放大的图片分辨率加倍

**Comment by nollinvoyd** [comment]
Looks good.

**Comment by Mr-VincentW** [comment]
> 有些时候图片太小了 鼠标悬浮上去后放大的图片也太小了 能不能加一个if判断 如果图片的分辨率小于某一个数值 放大的图片分辨率加倍

感谢补充。浮图秀目前暂不做图片的插值放大，如果不能获取到更大分辨率的图片且已有的原图比页面所展示出来的大，则倾向于展示已有原图。未来浮图秀会支持自由缩放。

您还可以选择报告您遇到该问题的网站，以便我查看是否可以单独适配之。如有此需要，请单独创建新的 issue，谢谢。
