### ISSUE TITLE
打开或刷新某些页面时，会有个字母“a”出现，页面加载完后消失

### ISSUE THREAD

**Issue by kidzgy** [Mr-VincentW/PhotoShow#167]
https://github.com/user-attachments/assets/db47f67e-6ddb-4af7-8a6f-d42310e0dec1

直接上视频。
WIN11+Firefox 128，只启用 浮图秀 扩展。

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题已于更新 4.43.1 修复。
