### ISSUE TITLE
【功能建议】希望增加复制图像到粘贴板功能（赋予快捷键shift+c或者自定义快捷键）

### ISSUE THREAD

**Issue by dente9** [Mr-VincentW/PhotoShow#168]
![image](https://github.com/user-attachments/assets/0f601522-3008-42ba-bfc5-8535f7c15b4d)
在edge浏览器中，可以对着图片右键点击‘复制图像’
然后按下快捷键’win+v‘粘贴板
![image](https://github.com/user-attachments/assets/4811bd03-bc8c-47fc-8f81-df3bdc74824e)

**Comment by Mr-VincentW** [comment]
感谢反馈，请参阅 #38 。
另：此功能预计会在未来实现。

**Comment by Mr-VincentW** [comment]
复制图片的功能已于更新 4.49 中实现，请参阅此前引述的 #38 。谢谢！
