### ISSUE TITLE
Edge浏览器从地址栏搜索进入百度界面再次点击“百度一下”会卡死

### ISSUE THREAD

**Issue by MonicaQvQ** [Mr-VincentW/PhotoShow#170]
搜索引擎默认为百度，从地址栏搜索进入百度界面后，如果点击“百度一下”再次进行搜素，页面会卡死，浏览器任务管理器显示百度网页占用CPU过高；以其他方式进入百度搜索则不会。

目前Edge版本为129.0.2792.52，128.0.2739.79版本也有这个问题，128.0.2739.67版本没有。

我开了15个扩展，一个一个关闭扩展试了一下，发现关闭AdGuard或者浮图秀就不会卡死了，但是如果同时只开我AdGuard和浮图秀两个扩展也不会卡死。AdGuard版本是4.4.22，更新时间是08月30日，浮图秀版本是4.44.2，更新时间是09月15日。AdGuard无变化，Edge和浮图秀有更新，所以我猜想是不是Edge或者浮图秀更新之后占用CPU变高了？我无从得知，所以来找你反馈一下。

**Comment by Mr-VincentW** [comment]
感谢反馈。

我个人测试未能复现此问题。请尝试如下操作：
- 提供您所使用的搜索关键字，或出问题时所访问的百度页面链接。
- 提供您所看到的页面的截图，尽可能包含全部页面内容。
- 提供其他与浮图秀公用时引发问题的插件列表，特别是能够修改页面内容的插件。
- 观察您所访问的页面上是否有持续变化的动画元素。
- 观察仅开启浮图秀时是否有此问题。

**Comment by MonicaQvQ** [comment]
随便搜索什么都可以。
我录了个视频，但是将近25M，传不上来，不知道你能不能提供个邮箱我传给你。
我把每个扩展单个关闭试过，只有在其他扩展也开启、浮图秀和AdGuard共同运行的时候会卡死，如果把所有扩展都禁用，只留浮图秀和AdGuard，，又不会卡死了。修改页面的插件还有这个脚本：[B站哔哩哔哩使用增强，全网VIP视频免费破解去广告，知乎使用增强，短视频无水印下载，油管、Facebook等国外视频解析下载等😈 (greasyfork.org)&nbsp;](https://greasyfork.org/zh-CN/scripts/469407-b%E7%AB%99%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA-%E5%85%A8%E7%BD%91vip%E8%A7%86%E9%A2%91%E5%85%8D%E8%B4%B9%E7%A0%B4%E8%A7%A3%E5%8E%BB%E5%B9%BF%E5%91%8A-%E7%9F%A5%E4%B9%8E%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA-%E7%9F%AD%E8%A7%86%E9%A2%91%E6%97%A0%E6%B0%B4%E5%8D%B0%E4%B8%8B%E8%BD%BD-%E6%B2%B9%E7%AE%A1-facebook%E7%AD%89%E5%9B%BD%E5%A4%96%E8%A7%86%E9%A2%91%E8%A7%A3%E6%9E%90%E4%B8%8B%E8%BD%BD%E7%AD%89)。
没有持续变化的动画元素。。
只开启浮图秀的话没有此问题。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-VincentW/PhotoShow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月24日(星期二) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mr-VincentW/PhotoShow] Edge浏览器从地址栏搜索进入百度界面再次点击“百度一下”会卡死 (Issue #170)






感谢反馈。

我个人测试未能复现此问题。请尝试如下操作：

提供您所使用的搜索关键字，或出问题时所访问的百度页面链接。

提供您所看到的页面的截图，尽可能包含全部页面内容。

提供其他与浮图秀公用时引发问题的插件列表，特别是能够修改页面内容的插件。

观察您所访问的页面上是否有持续变化的动画元素。

观察仅开启浮图秀时是否有此问题。

**Comment by MonicaQvQ** [comment]
> 感谢反馈。
> 
> 我个人测试未能复现此问题。请尝试如下操作：
> 
> * 提供您所使用的搜索关键字，或出问题时所访问的百度页面链接。
> * 提供您所看到的页面的截图，尽可能包含全部页面内容。
> * 提供其他与浮图秀公用时引发问题的插件列表，特别是能够修改页面内容的插件。
> * 观察您所访问的页面上是否有持续变化的动画元素。
> * 观察仅开启浮图秀时是否有此问题。

![QQ截图20240924173218](https://github.com/user-attachments/assets/af09325a-de0a-4ce2-9eab-06709a9533e7)
这个是扩展列表。

**Comment by Mr-VincentW** [comment]
感谢提供如此详实的信息，我会尝试能否复现你所遇到的问题。
视频烦请发往 vincentwang863@gmail.com，谢谢。

**Comment by MonicaQvQ** [comment]
> 感谢提供如此详实的信息，我会尝试能否复现你所遇到的问题。 视频烦请发往 [vincentwang863@gmail.com](mailto:vincentwang863@gmail.com)，谢谢。

我发过去啦，谢谢！

**Comment by Mr-VincentW** [comment]
我安装了你所启用的几乎所有插件并按照视频所示方式测试，依然未能复现你所遇到的问题😥。

不过从现象推测，可能是某个能够修改页面内容的插件移除了浮图秀必须的某些页面内容，浮图秀尝试重新注入并再次被移除，如是往复陷入死循环。建议检查你的 AdGuard 或篡改猴看是否有个性化的过滤设置或脚本导致此行为。

**Comment by MonicaQvQ** [comment]
这个是我的AdGuard设置文件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-VincentW/PhotoShow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月24日(星期二) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mr-VincentW/PhotoShow] Edge浏览器从地址栏搜索进入百度界面再次点击“百度一下”会卡死 (Issue #170)






我安装了你所启用的几乎所有插件并按照视频所示方式测试，依然未能复现你所遇到的问题😥。

不过从现象推测，可能是某个能够修改页面内容的插件移除了浮图秀必须的某些页面内容，浮图秀尝试重新注入并再次被移除，如是往复陷入死循环。建议检查你的 AdGuard 看是否有个性化的过滤设置导致此行为。

**Comment by Mr-VincentW** [comment]
没有任何附件？

**Comment by MonicaQvQ** [comment]
> 没有任何附件？

[adg_ext_settings_4.4.22_240924-202531.json](https://github.com/user-attachments/files/17122949/adg_ext_settings_4.4.22_240924-202531.json)
有的，从邮箱上传的的不知道为啥没显示。

**Comment by Mr-VincentW** [comment]
很遗憾我这边还是没能复现你所遇到的问题。
请逐个尝试仅开启某插件与浮图秀，观察可能的冲突来源。

**Comment by MonicaQvQ** [comment]
> 很遗憾我这边还是没能复现你所遇到的问题。 请逐个尝试仅开启某插件与浮图秀，观察可能的冲突来源。

我才发现邮箱里回的消息有一条没显示在github，不知道你收到了木有。
![image](https://github.com/user-attachments/assets/fcd3a6a3-e71a-4636-a8bb-f1e723739023)
这个是Picviewer CE+脚本反馈页面：https://greasyfork.org/zh-CN/scripts/24204-picviewer-ce/discussions/258871
我后来试了一下，发现如果同时打开AdGuard、浮图秀和Picviewer CE+，就会卡死，任意开其中两个则不会卡死。我还尝试了启用AdGuard但关闭设置里的所有选项，依然会卡死。

**Comment by Mr-VincentW** [comment]
你的 Picviewer CE+ 有特别设置吗？我使用默认设置依然未能复现你遇到的问题。

**Comment by MonicaQvQ** [comment]
> 你的 Picviewer CE+ 有特别设置吗？我使用默认设置依然未能复现你遇到的问题。

![1](https://github.com/user-attachments/assets/eb9fea52-34cc-40f3-bcb6-d70b7705d34e)
![2](https://github.com/user-attachments/assets/3225b7aa-addc-4149-960b-c95d9b94052f)
![3](https://github.com/user-attachments/assets/3688f4bf-9754-405d-9148-e670fa69fce2)
![4](https://github.com/user-attachments/assets/8e090318-b796-4f24-9634-f1640c6e907d)
![5](https://github.com/user-attachments/assets/19875c8f-3408-44dd-945c-a7a1151f6853)
图库选项里搜图站点是这些：
Google | https://www.google.com/searchbyimage?image_url=#t#
Yandex | https://yandex.com/images/search?source=collections&rpt=imageview&url=#t#
SauceNAO | https://saucenao.com/search.php?db=999&url=#t#
IQDB | https://iqdb.org/?url=#t#
3D IQDB | https://3d.iqdb.org/?url=#t#
Baidu | https://graph.baidu.com/details?isfromtusoupc=1&tn=pc&carousel=0&promotion_name=pc_image_shituindex&extUiData%5bisLogoShow%5d=1&image=#t#
Bing | https://www.bing.com/images/search?view=detailv2&iss=sbi&form=SBIVSP&sbisrc=UrlPaste&q=imgurl:#t#
TinEye | https://www.tineye.com/search?url=#t#
Sogou | https://pic.sogou.com/ris?query=#t#
360 | http://st.so.com/stu?imgurl=#t#
WhatAnime | https://trace.moe/?url=#t#
Ascii2D | https://ascii2d.net/search/url/#t#
Trace Moe | https://trace.moe/?url=#t#
KarmaDecay | http://karmadecay.com/#t#
ZXing QRCode | https://zxing.org/w/decode?full=true&u=#t#
ImgOps | https://imgops.com/#b#
应该是默认的。
以上是我的设置，是很久很久以前安装的了，印象里大部分设置没有动过。

**Comment by MonicaQvQ** [comment]
> 你的 Picviewer CE+ 有特别设置吗？我使用默认设置依然未能复现你遇到的问题。

有一点令我不解的是为什么我从百度首页搜索就不会卡死，从地址栏搜索就会卡死。

**Comment by Mr-VincentW** [comment]
我看你的视频里，当访问百度页面时，你的篡改猴似乎有两个脚本在运行？

**Comment by MonicaQvQ** [comment]
> 我看你的视频里，当访问百度页面时，你的篡改猴似乎有两个脚本在运行？

是的，还有一个就是我一开始提到的这个：https://greasyfork.org/zh-CN/scripts/469407-b%E7%AB%99%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA-%E5%85%A8%E7%BD%91vip%E8%A7%86%E9%A2%91%E5%85%8D%E8%B4%B9%E7%A0%B4%E8%A7%A3%E5%8E%BB%E5%B9%BF%E5%91%8A-%E7%9F%A5%E4%B9%8E%E4%BD%BF%E7%94%A8%E5%A2%9E%E5%BC%BA-%E7%9F%AD%E8%A7%86%E9%A2%91%E6%97%A0%E6%B0%B4%E5%8D%B0%E4%B8%8B%E8%BD%BD-%E6%B2%B9%E7%AE%A1-facebook%E7%AD%89%E5%9B%BD%E5%A4%96%E8%A7%86%E9%A2%91%E8%A7%A3%E6%9E%90%E4%B8%8B%E8%BD%BD%E7%AD%89
这个脚本我试过单独停用之后页面还是会卡住。

**Comment by Mr-VincentW** [comment]
看样子在我的环境里复现这个问题比较难。
是否尝试过万能的重装（浮图秀）大法？😂

**Comment by MonicaQvQ** [comment]
> 看样子在我的环境里复现这个问题比较难。 是否尝试过万能的重装（浮图秀）大法？😂

立刻尝试了重装（浮图秀）大法！还是卡住了😂
我从网上找了个4.40.1版本的，不会卡住。
我自己也记不清是从什么时候开始卡住的了，可能有半个多月，要不你把近期的几个版本都发我试试看？
对了，下面是我的浮图秀设置：
![QQ截图20240925112424](https://github.com/user-attachments/assets/3564e875-120e-4727-9cc9-05b85db3a1fc)

**Comment by Mr-VincentW** [comment]
在 4.40.1 和 4.44.2（当前版本）间有 6 次更新，请在附件中查收。
[PhotoShow Recent Versions.zip](https://github.com/user-attachments/files/17124832/PhotoShow.Recent.Versions.zip)

**Comment by MonicaQvQ** [comment]
> 在 4.40.1 和 4.44.2（当前版本）间有 6 次更新，请在附件中查收。 [PhotoShow Recent Versions.zip](https://github.com/user-attachments/files/17124832/PhotoShow.Recent.Versions.zip)

我挨个试了一下，发现是从4.44.0版本开始出现问题的，之前的版本都没有卡死。

**Comment by Mr-VincentW** [comment]
请按照如下步骤尝试：
- 安装附件中的浮图秀版本（[PhotoShow 4.44.0 Beta.zip](https://github.com/user-attachments/files/17125600/PhotoShow.4.44.0.Beta.zip)）。
- 通过地址栏默认搜索操作进入百度页面。
- 打开控制台（F12）。
- 点击“百度一下”按钮。
- 如果页面卡死，观察控制台是否有不断新增的浮图秀日志输出并反馈给我。

**Comment by MonicaQvQ** [comment]
我把在开发模式下暂停浮图秀这个选项取消之后试了确实有不断新增的浮图秀日志：
[www.baidu.com-1727243720392.log](https://github.com/user-attachments/files/17125961/www.baidu.com-1727243720392.log)
另外还有4.44.2版本的日志也一并给你：
[www.baidu.com-1727243869104.log](https://github.com/user-attachments/files/17125976/www.baidu.com-1727243869104.log)

**Comment by Mr-VincentW** [comment]
所以可以判断确实有某段脚本在不断移除浮图秀注入页面中的内容，只是由于我这里无法复现，不好定位来自哪个插件。我再做些尝试吧。

**Comment by MonicaQvQ** [comment]
> 所以可以判断确实有某段脚本在不断移除浮图秀注入页面中的内容，只是由于我这里无法复现，不好定位来自哪个插件。我再做些尝试吧。

好的好的，麻烦你了！世间万物都保佑你！

**Comment by MonicaQvQ** [comment]
哦对了，忘了说，那个4.44.0.Beta版本的看图片会出现一大一小两个图片重叠在一起的情况。
![image](https://github.com/user-attachments/assets/bdba3060-3169-4acb-bf93-66fcc159053f)
![image](https://github.com/user-attachments/assets/8840ec1b-c502-4abf-8942-b4eccbfb13b9)

**Comment by Mr-VincentW** [comment]
你这里出现的两个弹窗看着着实有些奇怪，如果同时运行两个浮图秀实例，弹出两个浮层是可能的；但浮图秀从不会在图片可以完整展示的情况下截断图片，所以你截屏里的那个小的弹层看着很不同寻常，更像是对源缩略图的一个轻微放大而不是浮图秀所该展示的样子。

至于卡死的问题，虽然我仍不能复现，但至少可以确定引发问题的直接原因。这些被反复移除的浮图秀页面元素将在浮图秀的下一个版本中被彻底革除。所以我想目前可以暂时搁置此问题，待下一版本发布后再观察。

**Comment by MonicaQvQ** [comment]
> 你这里出现的两个弹窗看着着实有些奇怪，如果同时运行两个浮图秀实例，弹出两个浮层是可能的；但浮图秀从不会在图片可以完整展示的情况下截断图片，所以你截屏里的那个小的弹层看着很不同寻常，更像是对源缩略图的一个轻微放大而不是浮图秀所该展示的样子。
> 
> 至于卡死的问题，虽然我仍不能复现，但至少可以确定引发问题的直接原因。这些被反复移除的浮图秀页面元素将在浮图秀的下一个版本中被彻底革除。所以我想目前可以暂时搁置此问题，待下一版本发布后再观察。

两个浮层同时出现，但不是每个图片都会出现两个浮层。而且我发现出现两个浮层的版本与会卡死的版本一致，即4.40.1-4.43.1版本不会卡死、单浮层，4.44.0-4.44.2版本会卡死，个别图片双浮层。

https://github.com/user-attachments/assets/b4452637-a609-46a5-b4e9-debb72882a9e

https://github.com/user-attachments/assets/247a2c7b-0633-4b3b-bba3-bcb9f695571a

我电脑里还有个5.1.1130.129版本的百分浏览器，我在上面试了一下同时开启AdGuard、Picviewer CE+和4.44.2版本的浮图秀，百度不会卡死。为排除是否是我Edge的设置导致的，我又在Edge上新建了个配置文件，所有浏览器设置为默认，只把地址栏搜索引擎改成了百度，只开AdGuard、Picviewer CE+和4.44.2版本的浮图秀3个扩展，依然会卡死，导致卡死的版本也是会出现双浮层，所以应该跟我的Edge设置无关，跟与Edge的兼容有关？

**Comment by Mr-VincentW** [comment]
再次感谢反馈。浮图秀已于更新 4.45 中彻底移除了可能造成您页面卡死的相关逻辑。请等待浏览器应用市场完成审核后上架。如问题仍未能解决，请重开此 issue，谢谢。

**Comment by MonicaQvQ** [comment]
> 再次感谢反馈。浮图秀已于更新 4.45 中彻底移除了可能造成您页面卡死的相关逻辑。请等待浏览器应用市场完成审核后上架。如问题仍未能解决，请重开此 issue，谢谢。

好的，是我该谢谢你开发了这么好的扩展。期待上架！
