### ISSUE TITLE
Issue with the names of downloaded files ✍️

### ISSUE THREAD

**Issue by thesla13** [Mr-VincentW/PhotoShow#171]
Hello, Mr. Vincent!

I've been having one issue with your most helpful and most wonderful extension.

<img width="347" alt="image" src="https://github.com/user-attachments/assets/fb4a4f34-e6df-442e-81a8-86b36a7ec6b0">

I've been having one issue with your most helpful and most wonderful extension.

The thing is that it can't seem to be able to properly name the images I ask it to download. It keeps naming the files with long rows of HEX-numbers. Whether, in the extension settings, I leave the "Filename" field blank, put <O> there, or anything for that matter, — it only ever uses those random names ((

I run MS Edge on MacOS. 

Thank you so much!

**Comment by Mr-VincentW** [comment]
Hi there,

Thank you for your feedback!
Please kindly attach some URLs of the pages where you had this issue with some screenshots if necessary. A manual review is needed to identify the problem.

**Comment by thesla13** [comment]
The strangest thing is that it happens _everywhere_ for me. No matter the site, no matter what. 

As an example, the first page currently open in my browser: https://en.wiktionary.org/wiki/glaive

![snap 2024 09 30 14-57-34](https://github.com/user-attachments/assets/254f6d64-19fc-4ca3-89e6-cd1e5b8ed25f)
![snap 2024 09 30 14-58-01](https://github.com/user-attachments/assets/06905dcc-1164-4dc0-99c9-c9fd6e9ae1e3)

The real name of the image can clearly be seen in lower left corner on the first screenshot. Yet it keeps naming it the random things.

I tried uninstalling and reinstalling — no help. Did check in the Dev version of Edge browser — it's the same.

**Comment by Mr-VincentW** [comment]
PhotoShow uses special techniques for downloading images, which may cause this issue. To retain original filenames, include the `<I>` or `<O>` keyword in your `Filename` settings.

For example, setting `PhotoShowDownloads/<I>` will save images in the `PhotoShowDownloads` folder with descriptive or original filenames. However, this depends on how the sites are structured, and it may not always work. Custom adjustments may be required for sites where this feature is essential. Feel free to let me know if you have any.
![image](https://github.com/user-attachments/assets/23d7438d-2375-4c4e-be6b-8825a0bcdf2c)

**Comment by thesla13** [comment]
Thank you for the reply, Mr. Vincent!

Yes, of course, I did try that. Nothing seems to produce any difference ((

![snap 2024 10 01 03-14-56](https://github.com/user-attachments/assets/31f04ea7-2920-40d5-9f77-fafd86d099e4)
![snap 2024 10 01 03-16-55](https://github.com/user-attachments/assets/eda34d17-0265-495c-8302-cc06ea5e745a)

Just to illustrate, I just used the exact name pattern you provided. It still puts them into the default Downloads folder, and still names them funny.

I'm sure it has to be something on my side, surely some conflict with some other extension (I run some 30+), and everything is perfectly fine with yours.
Still, maybe, some thought would cross your mind. Like, where could those hexadecimals come from? The groups of 8-4-4-4-12?

Thank you so much!

**Comment by Mr-VincentW** [comment]
Yea if you have other extensions managing file downloads, they may affect filenames. The general rule is that the most recently installed or updated extension takes priority. To check, simply disable all other download-related extensions and try again.

As for the random hexadecimal filenames, this happens because PhotoShow actually downloads files from an in-memory location rather than their original remote address. The hexadecimals are part of those in-memory addresses.

**Comment by thesla13** [comment]
You truly are a genius!

![snap 2024 10 01 04-06-59](https://github.com/user-attachments/assets/20e70653-90ab-411b-b0e2-a83cc8406657)

It was [Double-click Image Downloader](https://chromewebstore.google.com/detail/double-click-image-downlo/bkijmpolkanhdehnlnabfooghjdokakc), a remnant of the times past since before PhotoShow.

Everything works perfectly now! Thank you ever so much! 👯‍♀️🤸🪴
