### ISSUE TITLE
🤷‍♀️ Feature suggestion: modifier key to suspend operation

### ISSUE THREAD

**Issue by thesla13** [Mr-VincentW/PhotoShow#172]
If I may.

I think it could be very useful to be able to set a modifier key which, when held down, would block the extension.
I use show-on-hover, whitelist mode, and it does seem like too much work to look for the extension icon every time image-enhancing gets in the way and blacklisting the site, especially when chances are I will never ever visit it again.

And — there are sites where I want your extension to work at some times, and not to at others.

I really, really do think this is a sound idea. Hope you could look into it.

Thank you so much!

**Comment by Mr-VincentW** [comment]
Based on your needs, you can try the following:

- Press `Esc` to temporarily close the HD image overlay when it appears unexpectedly for a particular thumbnail.
- Use `Alt + P` to toggle PhotoShow on or off for the whole site you're on. This is functionally the same as toggling the switch on the PhotoShow settings popup.

The toggle shortcut can be customized here: [edge://extensions/shortcuts](edge://extensions/shortcuts).
![image](https://github.com/user-attachments/assets/7d976c67-16c2-47b0-80f7-fa65c2ad599f)

Let me know if this helps at all. Cheers.

**Comment by thesla13** [comment]
Yes, of course! And I do use a shortcut to enable/disable PS. 

But still, there are sites that have both sections where you want enhancement and where you don't. 
Even within one page. Say a product page in a store. They're all built different, sometimes a of sort enhancement like what PhotoShow provides is built in (like Amazon, if memory serves me) and PS messes with the presentation. But on that very page there would images, say in the customers' reviews section, where you would like to have it.
It's a very minor inconvenience, but an inconvenience still.

Again, I'm just saying: you do have the option to use PS in whitelist or blacklist mode. Which is symmetrical. You have an option to only use PS when a modifier key is depressed. An option to only _not_use_ it when a modifier key is depressed does seem to be a symmetrical addition.

I'm so sorry about the prolixy on a trivial matter ))

In any case, thank you again for your great work!

**Comment by Mr-VincentW** [comment]
Hmmm, I got your idea now! It sounds interesting and handy. I'll review it later to assess feasibility and implementation costs. You'll be updated on this issue. Cheers!

**Comment by Mr-VincentW** [comment]
Hi, PhotoShow has been updated to version 4.45 with a couple of great improvements, including the hotkey feature you required that lets you temporarily pause the extension! Now, pressing the `Esc` key not only closes the image viewer but also prevents it from popping out again while the key is held down. The new version will be available soon on each browser’s store, give it a try once it's released. Cheers!

**Comment by Mr-VincentW** [comment]
BTW, the hotkey for temporarily suspending PhotoShow has been changed from `Esc` to `X` from update 4.45.4 so that contextmenu won't be affacted while this key is held.
