### ISSUE TITLE
Break youtube subscribe button

### ISSUE THREAD

**Issue by Fred-Vatin** [Mr-VincentW/PhotoShow#174]
Firefox | OS              | Extension
------- | --------------- | ---- 
131.0.2 | Win 10 pro 22H2 | 4.45.1

When extensions is enabled, the subscribe button on a youtube channel can not be clicked. `Disable for this site` and reload page won’t fix the issue. Extension needs to be disabled in Firefox settings.

It worked until recently. I suspect the last update broke something.

When extension is enabled. Button can’t be clicked
![image](https://github.com/user-attachments/assets/e91aaa5d-220e-48cf-98e2-2a8d4a80e031)

When disabled. OK.
![image](https://github.com/user-attachments/assets/bd308170-6031-49d1-9637-d581f9f99abb)

You can test on any channel like https://www.youtube.com/@MrBeast

**Comment by Mr-VincentW** [comment]
Thank you for bringing this to my attention with all the details I need to identify the issue.
It has been fixed in update 4.45.2. Enjoy!
