### ISSUE TITLE
微博显示预览图异常

### ISSUE THREAD

**Issue by walklinewang** [Mr-VincentW/PhotoShow#175]
这两天发现出现了这个问题，会同时显示两张不同尺寸的图片出来，第一张小图直接显示，第二张大图稍微加载一会才显示，其它网站应该都是正常的

![image](https://github.com/user-attachments/assets/6934a90d-62af-4237-b38a-1c5fb02e15c4)

**Comment by Mr-VincentW** [comment]
感谢反馈。
- 您截图中图片显示错位的问题应该可以在刷新页面后消失。
- 另，虽然没有在您的截图中看到大小两张图的情况，但浮图秀近期的版本确实有过此问题。敬请期待最新的 4.45.2 版本通过审核后上架，将从根本上避免此现象。

如果更新后问题继续，请重开此 issue。
