### ISSUE TITLE
启用插件导致部分页面冻结

### ISSUE THREAD

**Issue by qh0814** [Mr-VincentW/PhotoShow#176]
### 问题描述
部分页面无法进行大部分操作，像是被冻结了一样。具体表现为：

- 无法使用鼠标左键与该页面进行**所有**交互，甚至包括其他插件的浮窗。
- 使用鼠标右键只能触发浏览器自带的菜单，菜单选项可以成功执行。
- 使用鼠标右键可以触发其他插件的功能，比如鼠标手势插件。
- 无法使用鼠标滚轮。
- 可以使用键盘操作，比如使用F5可以成功刷新页面，使用CTRL+S也可以触发保存操作。

### 尝试过以下方式来解决问题

- 关闭**所有其他插件**，只保留本插件，问题依旧存在。
- 关闭浏览器安装的所有插件，解决了问题。
- 只开启本插件，关闭插件内置的"对该网站启用"开关，问题依旧存在。
- 只开启本插件，在浏览器中的插件管理器中对本插件使用"单击拓展时启用"，并开启插件内置的"对该网站启用"开关，解决了问题。
- 在隐私模式不开启任何插件，解决了问题。
- 在隐私模式下只开启本插件，解决了问题。

### 暂时发现以下页面会出现这样的问题

- 通义千问聊天界面的效率选项 
https://tongyi.aliyun.com/efficiency/
- 360AI搜索进行搜索后的页面
https://so.360.com/

### 出现问题的环境
edge浏览器：版本 129.0.2792.89 (正式版本) (64 位)
插件版本：4.45.2

**Comment by shioryyy** [comment]
补充一个会出现冻结的页面：飞书云文档
例：https://zw73xyquvv.feishu.cn/wiki/UH5QwtUWtis1gTk4R6rcnWK2nZc

**Comment by MonicaQvQ** [comment]
我也有这个问题，例：https://www.kdocs.cn/l/cum7nAY4QpJb

**Comment by Mr-VincentW** [comment]
感谢各位支持，抱歉此次更新引入这个问题。
已在 4.45.4 中修复，敬请等待浏览器应用市场审核后上架。
