### ISSUE TITLE
opening a Twitter image redirects to 404 page.

### ISSUE THREAD

**Issue by gluid** [Mr-VincentW/PhotoShow#178]
absolutely love this extension, but as of recently if I open a Twitter image by TAB it instead opens it as
https://pbs.twimg.com/media/{hashhere}?=&format=jpg&name=orig
leading to a 404 page, whereas it should be like
https://pbs.twimg.com/media/{hashhere}?format=jpg&name=orig
can this, please, be fixed? thank you very much.
![image](https://github.com/user-attachments/assets/be260802-bf22-4e99-a11b-0811d54ab243)
![image](https://github.com/user-attachments/assets/c5264689-be2e-46e7-8966-523a1c7fd432)

**Comment by Mr-VincentW** [comment]
Thank you for reporting the issue. This will be addressed with the next update of PhotoShow.
Meanwhile, it'd be appreciated if you can attach the link of the original thumbnail or the twitter page so that I can verify the fix. Thanks.

**Comment by gluid** [comment]
the issue occurs with absolutely any image on Twitter, but if it's that unnecessary - I can provide a link to the original post.
https://x.com/aza_na/status/1846116302349283701

**Comment by Mr-VincentW** [comment]
This issue has been fixed in update 4.46 released today. Cheers.

**Comment by gluid** [comment]
it seems that the Chrome version hasn't been updated though...

**Comment by Mr-VincentW** [comment]
Please wait for the Chrome Web Store to complete reviewing the new version before your browser can fetch the update.

**Comment by gluid** [comment]
I see, thank you very much then, you're a life saver.
