### ISSUE TITLE
希望增加自动保存图片为jpg或png格式

### ISSUE THREAD

**Issue by jasonxu1191** [Mr-VincentW/PhotoShow#180]

**Comment by Mr-VincentW** [comment]
感谢反馈，预计会在未来版本实现，敬请期待。

**Comment by Mr-VincentW** [comment]
此功能已在更新 4.49 中实现，请等待各浏览器应用市场完成审核后上架。
更改图片保存格式的设置项如下图所示：
![image](https://github.com/user-attachments/assets/85a86ef2-59fc-4a92-bc87-2b5963485da1)
