### ISSUE TITLE
Update from 2024-10-20 broke cmd-C to copy text

### ISSUE THREAD

**Issue by garyking** [Mr-VincentW/PhotoShow#183]
Cmd-C is used in Chrome on Mac to copy text. Since the PhotoShow update on 2024-10-20, this shortcut no longer works. The extension hijacks "C" to copy the URL of the currently hovered image, even if I am not currently hovering over any image.

**Comment by Mr-VincentW** [comment]
Hi Gary, thank you for your feedback and sorry for the issue introduced in the last version. It has now been fixed in update 4.47.0. Please wait for browser app stores to complete their review before you can get the update. Cheers.
