### ISSUE TITLE
How to exclude certain images in flickr?

### ISSUE THREAD

**Issue by decembre** [Mr-VincentW/PhotoShow#184]
In photo page, Photoshow want preview the Principal photo itself.
TEST link:
https://www.flickr.com/photos/ima_gines/51986738975/in/pool-portrait_faces_open_minded_

If i use my CSS tweak, it work:
/* (new315) PHOTO PAGE - PhotoShow Adaptation :has()- FlickR - SUPP VIEWER FOR CERTAIN IMAGES (new315) */
/* src="https://live.staticflickr.com/65535/53399519370_8a4dbfba39_k.jpg"*/
.fluid.html-photo-page-scrappy-view #photoShowViewer:has([src*="_k.jpg"]) {
    position: fixed !important;
    display: none  !important;
    visibility: hidden !important;
    opacity: 0 !important;
    transform: unset !important;
    top: -100vh !important;
    pointer-events: auto !important;
    border: 1px solid red  !important;
}
BUT the Problem:
This CSS rule don't only exclude the principal photo, but too other small photo in the page that i want keep to be pre-viewed...

Can you add a way to achieve that ?

**Comment by Mr-VincentW** [comment]
Hey, please try ticking this option to avoid PhotoShow from displaying the viewer for "thumbnails" that are large enough:
![image](https://github.com/user-attachments/assets/37b5061b-751a-452a-ac37-099378a6768e)
Cheers.

**Comment by decembre** [comment]
Ok that's good:
i missed this option...
:-)

Thanks and fine work as usual.
