### ISSUE TITLE
与 智能反色 不兼容

### ISSUE THREAD

**Issue by QuarterQuell** [Mr-VincentW/PhotoShow#185]
![20241022](https://github.com/user-attachments/assets/24e1c541-3bde-4e4d-8087-4acf9548a66a)
更新4.47后，智能反色会导致弹出的图片被取反色，与底图不一致

**Comment by Mr-VincentW** [comment]
感谢反馈，请问“智能反色”是？

**Comment by QuarterQuell** [comment]
就是Edge商店的一个名叫 "SuperDarkMode" 的扩展，有“自适应深色”、"智能反色”和“自定义”3种使网页显示深色的模式。
智能反色会把弹出的图片给取反色，不过换成自适应就没有这个问题了。
对比了其他几个同类插件，我有发现了更好用的插件，最后确定应该是SuperDarkMode自己的问题吧，算了这个问题就先关闭吧

**Comment by Mr-VincentW** [comment]
已在更新 4.48.0 中采取措施减少弹出大图受此外部样式影响的可能性，谢谢反馈。
