### ISSUE TITLE
和云顶阵容模拟器https://tactics.tools/zh/team-builder冲突BUG

### ISSUE THREAD

**Issue by fgo1212** [Mr-VincentW/PhotoShow#186]
和云顶阵容模拟器https://tactics.tools/zh/team-builder有冲突BUG，启用了扩展，装备就不能放到棋子上去把这个网站排除启用也还是不行，禁用扩展就正常

**Comment by Mr-VincentW** [comment]
感谢反馈，已在更新 4.48.0 中修复此问题。敬请等待各浏览器应用市场完成审核后上架。
