### ISSUE TITLE
chrome使用第三方下载管理拓展时，浮图秀的文件命名功能失效

### ISSUE THREAD

**Issue by Tgkkez** [Mr-VincentW/PhotoShow#188]
chrome使用RegExp Download Organizer（下载文件分类）、Chrono Download Manager（下载管理器扩展）等时，浮图秀下载的图片是默认文件名，自定义的重命名规则失效

**Comment by Mr-VincentW** [comment]
感谢反馈。Chrome 插件操作下载文件名的方式比较特殊。简而言之，当有多个插件都能干预下载文件名时，彼此无法妥协。这个问题无解。
