### ISSUE TITLE
Can't use "C" shortcut on YouTube to toggle captions, when this extension is enabled

### ISSUE THREAD

**Issue by garyking** [Mr-VincentW/PhotoShow#189]
The letter "C" used for keyboard shortcuts, such as to enable and disable captions on YouTube videos, does not work when this extension is enabled.

Similar issue to #187.

**Comment by Mr-VincentW** [comment]
Hi, thanks for reporting the issue! It has been fixed in update 4.49. Please kindly wait for the new version to get available in each browser's app store after the review process. Cheers!
