### ISSUE TITLE
Whitelist/Inverted Blacklist setting

### ISSUE THREAD

**Issue by CapoFantasma97** [Mr-VincentW/PhotoShow#19]
Hi,
Can you add an option so that by default the extension is disabled, and therefore one decides for which websites to turn it on?

It can be unwanted or quite annoying for a majority of websites, me personally I'd like to use it only on a few specific websites, and disabling them one by one is very time consuming (and it will keep affecting any newly browsed website, so it's a neverending job).

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. I will consider it. 
In the future, PhotoShow is likely to provide either a toggle item for setting the default enable/disable state for all the websites as you said or a whole list of websites it supports where you can enable/disable the websites with bulk operation.

**Comment by Mr-VincentW** [comment]
PhotoShow supports whitelist mode since update 4.24. You may turn it on from the settings panel as per the screenshot below. Cheers.
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/0ad1edb4-50d0-4a0c-8400-2f532ee99487)
