### ISSUE TITLE
"Activation Mode" does not work with Alt

### ISSUE THREAD

**Issue by garyking** [Mr-VincentW/PhotoShow#190]
I set Activation Mode to require holding Alt (also known as Option on my Mac). Since the latest update, this doesn't work anymore. When I hold the Option key on my Mac and hover my cursor over an image, it doesn't show the zoomed in version. If I set Activation Mode to None, then hovering over images works fine.

**Comment by Mr-VincentW** [comment]
Yep, my apologies. That was a new bug introduced with update 4.49.1.
It has been fixed in 4.49.2, which is still under review for Chrome Web Store.

Thank you for your support!
