### ISSUE TITLE
复制粘贴时会在末尾加上 a 

### ISSUE THREAD

**Issue by WilliamK7** [Mr-VincentW/PhotoShow#193]
https://github.com/user-attachments/assets/1b91965a-82de-4365-8e32-62709e874e0e

可能和 https://github.com/Mr-VincentW/PhotoShow/issues/167 有关？

**Comment by Mr-VincentW** [comment]
感谢反馈！
此问题已在更新 4.52.0 中修复，请等待各浏览器应用市场完成审核后上架。
