### ISSUE TITLE
使用插件导致 S 键故障

### ISSUE THREAD

**Issue by NeilTohno** [Mr-VincentW/PhotoShow#198]
![2](https://github.com/user-attachments/assets/e7990d1c-593c-4935-b0a0-0f438c2137c4)

大佬你好，我使用新版发现故障了，
关掉快捷键 S 键就正常了，辛苦了

**Comment by Mr-VincentW** [comment]
感谢反馈。
当鼠标悬停在缩略图且某快捷键被启用时，为防止与网站原生快捷键操作冲突触发非预期的行为，浮图秀会阻断相应按键事件的进一步执行。
如果您遇到的情况与上述不同，请进一步提供更多细节，谢谢。

**Comment by NeilTohno** [comment]
> 感谢反馈。 当鼠标悬停在缩略图且某快捷键被启用时，为防止与网站原生快捷键操作冲突触发非预期的行为，浮图秀会阻断相应按键事件的进一步执行。 如果您遇到的情况与上述不同，请进一步提供更多细节，谢谢。

你好，这个是测试键盘按键的网站，并不存在网站快捷键
https://keyboard.bmcx.com/

**Comment by Mr-VincentW** [comment]
感谢补充。
首先，这是通用逻辑，并不针对特定网站，所以会在所有网站生效。
另外，通过测试您所提供的网站，确实发现一处错误导致了仅`S`按键受到影响而其他按键正常。该问题会在浮图秀下次发版时修复，我会再次更新本 issue。谢谢。

鉴于该页面上似乎也没有太多需要通过浮图秀查看的图片，目前您可以选择针对该网站关闭浮图秀：
![image](https://github.com/user-attachments/assets/1dd35915-f81f-43f1-b667-ca1dfe0fe739)

**Comment by kokojacket** [comment]
使用portainer 进ssh后，无法键入s
![image](https://github.com/user-attachments/assets/b53c3bce-db5d-4bd0-ad2c-b89960f8389f)
@Mr-VincentW

**Comment by Mr-VincentW** [comment]
> 使用portainer 进ssh后，无法键入s

感谢补充，如前所述，已有一处导致`S`键失效的问题被定位并将在浮图秀下次更新时修复，我将在发版后再次更新本 issue，敬请保持关注。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.58.0 修复，敬请等待各浏览器应用市场完成审核后上架。谢谢。
