### ISSUE TITLE
微博图片无法正常用扩展下载 没有访问权限

### ISSUE THREAD

**Issue by coccvo** [Mr-VincentW/PhotoShow#199]
微博中的图片用tab新标签打开或者用s下载，该链接没有访问权限403，导致失败
例如
https://wx1.sinaimg.cn/original/856f8cecly1hwr5ul6zluj20xc0xcq57.jpg
要把original换成large才行
https://wx1.sinaimg.cn/large/856f8cecly1hwr5ul6zluj20xc0xcq57.jpg

希望扩展可以对此修改

**Comment by coccvo** [comment]
浏览器内核更新后解决了

**Comment by Mr-VincentW** [comment]
感谢反馈，确实发现一处可能导致微博图片偶发性下载失败的问题并已在更新 4.58.0 修复，敬请等待各浏览器应用市场完成审核后上架。谢谢。
