### ISSUE TITLE
请求添加快捷键将图片复制到剪贴板

### ISSUE THREAD

**Issue by kinrt** [Mr-VincentW/PhotoShow#20]
请求添加快捷键将图片复制到剪贴板，可以粘贴到聊天窗口，图片编辑软件等。

**Comment by Mr-VincentW** [comment]
很遗憾，迄今为止浏览器插件还没有能力向系统剪贴板写入图片数据。未来当相关功能得到支持，浮图秀会跟进实现此需求。谢谢。

**Comment by kinrt** [comment]
能否提供选项支持，鼠标从小图移到大图，大图继续显示，然后可以使用右击菜单复制图片到剪贴板呢。当前是鼠标移除小图大图就不显示了。非常感谢！

**Comment by Mr-VincentW** [comment]
目前变通的做法是您可以使用 Tab 快捷键在新窗口中打开图片，然后右键复制之。另请参阅此 issue #16 .
