### ISSUE TITLE
希望能够自由设置视图模式

### ISSUE THREAD

**Issue by Synneither** [Mr-VincentW/PhotoShow#200]
我设置的触发模式为鼠标悬停。在b站使用时。迷你，轻量模式时在遇到长图时显示的太小。
<img src="https://github.com/user-attachments/assets/330d254a-670c-4444-93e4-289a1ce54280" width="200px" height="250px">
而自动模式在遇到头像时显示太大。
<img src="https://github.com/user-attachments/assets/791b6858-05b4-4bd9-9478-f8e2393340c0" width="300px" height="200px">
希望能够设置当图片高度超过某某时自动切换为自动模式。或者说当图片尺寸比为头像常见的1:1时切换为迷你模式。

**Comment by Mr-VincentW** [comment]
感谢反馈。
在自动模式下的常规图片会以不超过可获取的大图尺寸或屏幕可用空间最大可容纳的尺寸显示，以二者中较小的为准。这保证了图片得到尽可能大的展示。您所展示的实例恰好该用户使用了比较大的头像图片。

混用视图模式或根据图片比例随意改变视图模式会造成很大的困扰，使用户无法对软件的行为产生稳定预期，故无法采用此策略，敬请谅解。
