### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by zhangch259** [Mr-VincentW/PhotoShow#21]
推特网页现在有自己的快捷键，按s保存图片和推特的分享推文冲突，不知道可不可以更改保存图片的快捷键或屏蔽推特自己的快捷键

**Comment by Mr-VincentW** [comment]
感谢反馈。 基于安全原因，浏览器插件被设计为无法干预宿主页面原生逻辑，故此浮图秀无法屏蔽推特页面原有快捷键行为。未来浮图秀将提供自定义自身快捷键的支持，但仍可预见的是——无法完全避免与所有网站的快捷键都不冲突，因为各网站都有不同的快捷键定义。

**Comment by Mr-VincentW** [comment]
再次感谢反馈，浮图秀已于 4.7.0.0 版本起修复快捷键冲突问题。欢迎试用。
