### ISSUE TITLE
开启扩展时在哔哩哔哩的直播间内会导致无法送出礼物

### ISSUE THREAD

**Issue by muchen2541** [Mr-VincentW/PhotoShow#24]
开启扩展时在哔哩哔哩的直播间内会导致无法浮出送礼小窗，在所有的礼物列表中永远只有第一行的第一个礼物可以浮现送礼小窗口，只要将扩展关闭就能立刻正常，希望修复此bug

**Comment by Mr-VincentW** [comment]
感谢反馈！已于更新 4.9.0.0 中修复此问题，敬请期待上架。
