### ISSUE TITLE
更新后淘宝的图片预览问题

### ISSUE THREAD

**Issue by 1169833804** [Mr-VincentW/PhotoShow#27]
更新之后，淘宝的商品页面内的商品规格图片和商品详情图片都不能预览原图

**Comment by Mr-VincentW** [comment]
感谢反馈。
浮图秀在更新 4.9.1.0 中引入一个较为严重的 bug，致使其在多个网站页面中的一些图片上无法正常工作。此问题已于更新 4.9.2.0 中修复，待各浏览器应用市场审核结束后即可上架。

如果您此处的“商品详情图”指的是页面主要区域内的大幅商品详情图，则更大的可能是因为浮图秀从更新 4.7.0.0（2021-7-4 发布）起，默认不对尺寸超过窗口可视区面积 25% 的图片展示大图预览；但相关的快捷键仍可使用，比如在新 Tab 中打开大图，或复制大图地址、下载大图等。如果您想取消此行为，可在浮图秀设置面板中更改：

![image](https://user-images.githubusercontent.com/54405631/131206270-de8cdc83-e349-43d6-90e0-31e63f60c425.png)

**Comment by 1169833804** [comment]
预览商品详情图在上一个版本还是可以的，所以和这个激活豁免应该是没有关系

**Comment by Mr-VincentW** [comment]
> 预览商品详情图在上一个版本还是可以的，所以和这个激活豁免应该是没有关系

请等待更新至 4.9.2.0 后再次尝试，谢谢。
