### ISSUE TITLE
在微博页面 快捷键无效

### ISSUE THREAD

**Issue by fodereas** [Mr-VincentW/PhotoShow#28]
在最需要使用的微博网页中，鼠标放上去显示出大图，然而快捷键全部无效，无法按S保存大图
在别的网页好像都正常
不知道是不是快捷键冲突 还是别的原因
希望能优化一下。。
能否自定义快捷键呢？哪怕只自定义保存键

又发现，当点击【插件图标】显示出浮图秀设置界面时，快捷键才会有效
![image](https://user-images.githubusercontent.com/25607187/131792466-b74dc331-5768-4b0d-b990-5738b796cb6f.png)

**Comment by Mr-VincentW** [comment]
感谢您的反馈。我个人测试没有发现此问题。请确认您是否有其他潜在可能影响页面快捷键交互的插件在微博页面工作。如果问题依旧，您可以继续向我反馈，同时烦请附上具体页面链接及您的浏览器名称、版本。谢谢。

**Comment by fodereas** [comment]
找到了

冲突的脚本：
https://greasyfork.org/zh-CN/scripts/381682-html5视频播放器增强脚本
冲突的插件：
https://microsoftedge.microsoft.com/addons/detail/supercopy-超级复制/nhiheekdcnmfbapkmpbhmplfddenhjic

**Comment by Mr-VincentW** [comment]
感谢补充。浮图秀未来预计会支持自定义快捷键，但依旧无法避免与其他插件产生可能的冲突，插件之间相互独立，无法也不应干预彼此。
