### ISSUE TITLE
导致网页中的 before, after 按钮功能都失效

### ISSUE THREAD

**Issue by kiddin9** [Mr-VincentW/PhotoShow#29]
*:before, *:after {
    pointer-events: none !important;
}
这条语句导致网页中所有的 before, after 按钮功能都失效了.

**Comment by Mr-VincentW** [comment]
感谢反馈。这是有意设计的。

很多网站使用 pseudo-elements 来给图片添加遮罩、小标签等缀饰，浮图秀目前通过 mouseover 事件侦测目标图片，这些叠加在图片之上的缀饰会阻碍浮图秀正常展示大图（鼠标移过时大图预览浮层将消失）。鉴于 pseudo-elements 并不能承载事件触发（相关标准截至本条回复发出时还没有被任何浏览器厂商支持），此“入侵性”方案预期不会严重影响页面原有功能，至多只是影响到 pseudo-elements 的 hover 样式。故而权衡后决定采用。

我正在试验另一种非入侵性的探测目标图片的方案，如果可行，未来浮图秀将不再通过 pointer-events: none 干预页面任何原有样式。

您如果发现任何基于此产生的严重影响，欢迎补充详述，我将重新评估该方案。

我将保持此 issue open 直到新的方案有一个结果。

**Comment by Mr-VincentW** [comment]
此问题已于更新 4.45 中得到解决。浮图秀不再向页面注入 `pointer-events: none` 样式。
请等待浏览器应用市场完成审核后上架。谢谢。
