### ISSUE TITLE
能删掉“图片加载中”的提示吗

### ISSUE THREAD

**Issue by willbeevil** [Mr-VincentW/PhotoShow#3]
能删掉“图片加载中”的提示吗，感觉有些鸡肋
大图显示前这个提示一闪而过，强迫症很难受

**Comment by Mr-VincentW** [comment]
感谢反馈。“加载中”的消息展示一直以来都是一个难以两全齐美的方案：

- 对于图片加载比较快的情况，这个消息的确会“一闪而过”，给人比较“鸡肋”的感觉（当然，可以人为延长这个消息的展示时间以使其看上去更有“存在感”，但浮图秀选择尽快给用户展示出图片而非“为了提示而提示”）。

- 但当图片加载较慢时，如果没有任何提示，用户在图片加载出来前会觉得浮图秀未能响应。这意味着，如果没有这个提示，用户对该图片的大图能否展示、何时展示出来将缺少心理预期。一个很可能的结果是：用户会多次将鼠标移入移出缩略图以尝试“激活”浮图秀并在几番尝试后发现“浮图秀有时工作，有时不工作”。如果你有过类似经历，就会明白这将是更糟糕的体验。

事实上，当前浮图秀也并非在每次展示图片前都显示“加载中”的消息，这里有一个时间阈值的设定，当图片加载足够快时，“加载中”消息是不会展示出来的。但同样道理，因网络环境、图片大小而异，这个时间阈值也没有办法保证在任何时候都表现得“刚刚好”。

未来，浮图秀可能会考虑让这个时间阈值的设定更“智能”——根据用户网络环境及不同网站图片资源的加载时间来动态调整，但不会彻底取消该提示。当然，也不排除会添加一个配置项，让用户自己来决定是否将其关闭。如果您有更好的方案，也欢迎继续留言贡献您的智慧，谢谢！

**Comment by willbeevil** [comment]
谢谢回复，个人觉得“添加一个配置项，让用户自己来决定是否将其关闭”这个方案很棒，兼顾了用户的不同需求，期待新版本

**Comment by Mr-VincentW** [comment]
再次感谢您的反馈。浮图秀已于版本 4.7.0.0 起添加了“**显示图片加载状态提示**”的设置项，您可以通过此来关闭加载消息。
祝您使用愉快！
