### ISSUE TITLE
建议增加复制图片功能

### ISSUE THREAD

**Issue by o-ut-man** [Mr-VincentW/PhotoShow#38]
现在只能先下载后复制，是否能实现直接复制的功能？

**Comment by Mr-VincentW** [comment]
感谢反馈。向系统剪贴板复制二进制内容是高危行为，所以各浏览器目前都没有向插件开放完善的复制操作支持。

有变通的方案可以在 Chrome 浏览器下实现图片复制，但并不完美。复制带有透明通道的图片时会使透明通道丢失（透明部分将变成纯色填充）。

浮图秀将持续关注相关进展并在条件成熟时实现相关功能。

另外，您现在也可以选择先在新标签中打开图片然后右键复制，可能比先下载再复制稍稍方便一些。

**Comment by Mr-VincentW** [comment]
感谢反馈。复制图片的功能已于更新 4.49 中实现，请等待各浏览器应用市场完成审核后上架。新的复制图片的快捷键是 `Alt + C`，此操作同样可通过右键菜单完成：
![image](https://github.com/user-attachments/assets/82db5f09-2eb1-411b-8047-95c1113fafe1)
