### ISSUE TITLE
BUG反馈：使用Ctrl+tab 与Ctrl+shift+tab切换标签页时会意外激活附图秀

### ISSUE THREAD

**Issue by Harrydi2006** [Mr-VincentW/PhotoShow#39]
BUG反馈：使用Ctrl+tab 与Ctrl+shift+tab切换标签页时会意外激活附图秀显示图片 浏览器版本： Opera GX LVL3 (core: 82.0.4227.50)
标识：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.50 (Edition GX-CN)
![GIF 2022-1-13 12-01-10](https://user-images.githubusercontent.com/50307581/149263765-2d320112-d870-45f3-a197-8987fb6d6818.gif)
![微信截图_20220113120229](https://user-images.githubusercontent.com/50307581/149263824-8babc6ec-570f-413e-b1d4-cf9caeb060b8.png)

**Comment by Mr-VincentW** [comment]
感谢您的反馈及对问题的详尽描述！

因为您所设置的激活模式是 **Ctrl + 鼠标悬停**。所以当鼠标悬停在缩略图上并且您的 Ctrl 键被按下时，浮图秀便会激活展示大图，这是符合预期的。

通常，用户按下多个组合快捷键的时序并不能保证绝对同步；且浮图秀有一些包含多个组合键的快捷键操作（例如旋转）；加之用户行为可能有反复（比如某些键按下又放开）。所以如果浮图秀等待检测是否有其他组合键被按下以及判断这些组合键及用户操作变化的真正意图，将会使真正的展示大图行为延迟且表现“不稳定”。这引入了过度的干预且可能事与愿违。综上，该问题不被视为一个 bug 且将保持现状。如果您有其他想法，欢迎进一步讨论，谢谢！
