### ISSUE TITLE
求支持下cangku网站

### ISSUE THREAD

**Issue by bai12123** [Mr-VincentW/PhotoShow#43]
支持下cangku.icu网站，现在提供的基本支持，文章封面显示的不是原图，不是很清晰。另外仓库网站有时候会变域名，但基本都是cangku.*

**Comment by Mr-VincentW** [comment]
感谢反馈。我查看了下 cangku.icu，浮图秀对其提供的基本支持已经展示了该网站所提供的最大分辨率图片。似乎没有发现有其他更大分辨率的图片展示入口。您可以进一步补充说明。

**Comment by bai12123** [comment]
举例cangku.icu/archives/197688这篇文章，点击进去明显看到了更大的封面图？在外面的帖子列表浮现出来的小了。不知道是否是获取的图片不对
![Snipaste](https://user-images.githubusercontent.com/99849852/162622476-1644657c-878e-4d4c-b406-ea73846b8553.png)

另外关于展示浮图的一个细节，在一些网站（比如pixiv，yande等），获取的浮图是否偏小，图片顶部/底部距离浏览器顶部/底部有空隙（如图），我举例的这2个图片实际原图会更大，那么在展现浮图的时候不应该尽量展现大图吗
![Snipast2e](https://user-images.githubusercontent.com/99849852/162623360-d5be91db-dfb3-4644-8895-51aa82cfbf51.png)
![Snipast22e](https://user-images.githubusercontent.com/99849852/162623362-031eb23c-0369-4e71-88b7-9db2882e51b0.png)

**Comment by Mr-VincentW** [comment]
针对您提出的两个问题：

1. 对于 cangku.icu 网站来说，似乎只有封面图片尚有些许解析的价值，具体到文章内部的图片，我似乎没有看到更大分辨率图片的链接？对于封面图片的适配工作会在浮图秀后续更新中完成。

2. 浮图秀大图弹层距离浏览器窗口的边距是特意保留的——大图弹层并不会填充满整个浏览器窗口，这是浮图秀所会占据的屏幕空间上限。此举一来是出于设计美观的考虑；再者是为了给用户一个明确的视觉指示——这是一个弹层，而非页面原生内容。这是基于交互细节的考量，不这么做会在特定场景下带来更多麻烦。

   况且这个边距尺寸很小，所以对图片最终展示尺寸的影响相信可以忽略不计。另外，这并不影响下载图片的尺寸，当您下载或在新窗口中打开该图片时，得到的依然是浮图秀所能获取到的最大尺寸的“原图”。

   另外，如果您想在浮图秀弹层中查看原始尺寸的大图细节，欢迎尝试“全景”模式（可通过浮图秀设置面板永久开启，或在启用相应的快捷键后，在浏览大图的过程中随时切换）。

**Comment by Mr-VincentW** [comment]
Need to keep this open until the work around cangku.icu is done.

**Comment by Mr-VincentW** [comment]
cangku.icu has been added with update 4.16.1. Cheers!
