### ISSUE TITLE
图片显示的新方法

### ISSUE THREAD

**Issue by bai12123** [Mr-VincentW/PhotoShow#45]
从Powerful Pixiv Downloader里看到的功能，在这里提一下吧。保持原来的弹出方式不变，增加一种新方式：鼠标指针在缩略图上时，长按鼠标右键，于鼠标指针正中间弹出原图  #44，弹出的浮图显示为原图大小（全景图片），可鼠标滚轮缩放#32，可移动鼠标上下左右卷动图片，可右键图片保存复制等，写到这里看到#23有人提了这个。全景模式是因为旁侧空间不够大，无法完整加载原图，所以才需要卷动，所以增加一个新的弹出方法，并不会对原模式产生干扰，应该说新模式扩展了全景视图功能
![Snipaste_](https://user-images.githubusercontent.com/99849852/162483630-1a620589-4449-483d-8ea0-870be2d1f393.png)
![Snipaste2_](https://user-images.githubusercontent.com/99849852/162483648-883e681f-05aa-47d3-80c1-829a870f6491.png)
![Snipaste3_](https://user-images.githubusercontent.com/99849852/162483660-86548940-c914-4ae1-a759-285f4d6325ef.png)

**Comment by bai12123** [comment]
顺便再说个bug，yande.re其他的页面都能正常预览缩略图，唯独热门页面（popular）无法预览

**Comment by Mr-VincentW** [comment]
感谢反馈。全屏模式的展示会在浮图秀未来版本中提供，只是预计会需要比较久的开发周期，敬请期待。
另，从更新 4.16 起，浮图秀已对 yande.re 提供了专门适配。

**Comment by bai12123** [comment]
konachan.com，konachan.net网站帖子和热门都不行。其他图片站我没有测。另外问一句README_zh-CN.md里的项目进展大概什么时候可以，有点期待了

**Comment by Mr-VincentW** [comment]
这些网站需要专门适配，我会在后续更新中跟进。

README 里的项目进展只是记录了一些未来计划，浮图秀是一个业余项目，我工作比较忙，所以并没有固定的时间可以投入到其开发中来。短期内我还是会尽量跟进一些开发量不算太大的需求；但对于比较重大的变更，就只能等重构后实现了。理想的时间点是在今年年底浮图秀十周年之际，实际能否实现，还是未知数。

**Comment by Mr-VincentW** [comment]
Need to keep this open as a reminder for the work on konachan.com.

**Comment by Mr-VincentW** [comment]
Konachan has been added with update 4.16.1. Cheers.

**Comment by Mr-VincentW** [comment]
Hi, 再次感谢反馈。浮图秀已在本版 4.62.0 中添加新的“浮窗定位”选项“中央”，勾选后可在浏览器窗口居中全幅展示大图，敬请试用。

![Image](https://github.com/user-attachments/assets/7e1e9cec-69ad-41ae-bf23-3a53f167f721)

另，直接复制大图到剪贴板的功能也已在版本 4.49.0（发布于 2024-10-27）中实现，抱歉未能及时更新本 issue。
