### ISSUE TITLE
Cannot close some magnified images

### ISSUE THREAD

**Issue by nollinvoyd** [Mr-VincentW/PhotoShow#46]
Firefox 99, PhotoShow 4.16.0

Here is an example.  When you hover over the top panel, you have to disable PhotoShow from the toolbar button to shrink the image back to normal size.

[https://www.reddit.com/r/DataHoarder/comments/gig2w3/is_mipony_safe_to_use/](url)

**Comment by Mr-VincentW** [comment]
Sorry I couldn't manage to replicate this issue. It'd be easier for me to figure out the potential problem if some screenshots can be attached along with some description of the interaction on this page that led to this issue, if necessary. Thanks.

**Comment by nollinvoyd** [comment]
Here is the link again https://www.reddit.com/r/DataHoarder/comments/gig2w3/is_mipony_safe_to_use/

![photoshow2](https://user-images.githubusercontent.com/20844322/162800660-f2140948-9d85-4652-9e09-1f89d9da45b6.png)

See the cursor on the top image:

![photoshow](https://user-images.githubusercontent.com/20844322/162800816-b76ed8e0-eed6-4aa4-8aa4-65546203f40c.png)

See the cursor below the images

![photoshow3](https://user-images.githubusercontent.com/20844322/162801432-919d3ac0-cda5-49dd-8614-e5b09a0a73fa.png)

**Comment by Mr-VincentW** [comment]
This issue has been fixed with update 4.16.1. Cheers!
