### ISSUE TITLE
Settings are not saved while Firefox is restarted

### ISSUE THREAD

**Issue by Delgan** [Mr-VincentW/PhotoShow#5]
Hi!

I just updated PhotoShow to v4.4, the new features are great! However, I noticed what looks like an unfortunate regression: settings are not saved across Firefox sessions. :confused: 

![Peek 2020-04-20 19-04](https://user-images.githubusercontent.com/4193924/79779035-f4b37e80-8339-11ea-9c31-ef16f5689fa4.gif)

Maybe is it related to my configuration? Do you have any idea where I should look at, please?

I'm using Firefox 74.0.1 on Arch Linux. Also, I tried to re-install PhotoShow but it changed nothing.

**Comment by Mr-VincentW** [comment]
Hi Delgan,

Thank you for giving your feedback again and my apologies for the issue. It was caused by a recent update introducing a compatibility problem for Firefox. It has been fixed in the latest update 4.4.1. Please update PhotoShow in your browser.

Thank you.

**Comment by Delgan** [comment]
This is working perfectly well now! :tada: 

Thanks a lot for the quick fix and your great work!
