### ISSUE TITLE
🐛: 影响页面正常功能

### ISSUE THREAD

**Issue by Germxu** [Mr-VincentW/PhotoShow#52]
出现网站示例 :  https://www.naiveui.com/en-US/os-theme/components/carousel
在不少这种页面布局下, 左侧菜单点击出现无法正常跳转的问题, 希望可以查看解决一下, 
或者我这边有时间来帮助查找下原因也可以, 我还有一些优化思考, 希望一起参与, 谢谢

**Comment by Mr-VincentW** [comment]
感谢反馈。这是浮图秀的一个特殊图片探测机制所带来的副作用，当然，也和该网站实现细节的合理性有关。浮图秀在未来会尝试更改该探测方式以消除此副作用，但在此之前，鉴于该网站并没有多少图片需要放大，建议您在浮图秀配置面板中对该网站停用浮图秀。
