### ISSUE TITLE
youtube(https://www.youtube.com/)使用有问题。

### ISSUE THREAD

**Issue by iT0toro** [Mr-VincentW/PhotoShow#53]
https://www.youtube.com/ 鼠标放到视频缩略图是会有个浮动效果，导致插件无法查看图片。Microsoft Edge
Version 103.0.1264.37 (Official build) (64-bit)。PhotoShow 4.17

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题由 YouTube 近期的网站更新所致并已于浮图秀 2022-05-28 的更新中修复。请留意更新您的浮图秀到最新版本 （4.17.1 2022-06-21）。如果问题仍然存在，您可以通过邮件与我取得进一步联系或在此追加出问题页面的具体链接并描述复现问题的步骤，谢谢。
