### ISSUE TITLE
希望能保存高清图片时能自定义下载保存的路径

### ISSUE THREAD

**Issue by Abingbo** [Mr-VincentW/PhotoShow#55]
您好，我是一个设计工作者，插件非常好用，我平时会使用插件下载保存很多的参考图片。
但保存后会默认下载到浏览器的默认文件夹，希望这个插件能设置单独设置将图片保存到一个自定义文件夹的功能。
因为下载的默认文件夹通常不作为我们设计图片的保存路径，只时用来放置其他的下载文件。
这样就不需要下载后重新对图片移动整理了。

**Comment by Mr-VincentW** [comment]
感谢反馈。

浮图秀允许设置下载文件名及路径，请在浮图秀设置面板中修改“**文件命名**”。例如：设置为 `我的目录/<O>` ，浮图秀将以原始文件名的形式将图片保存至“**浏览器下载目录/我的目录/**”下。如果希望按照不同的网站域名再区分子目录，还可以将之设置为 `我的目录/<H>/<O>`。
![image](https://user-images.githubusercontent.com/54405631/178096906-cdc0403f-6504-45b2-a1fb-567ea4393009.png)

浏览器插件没有权限直接将文件保存至非浏览器默认下载路径，如果您有此需要，可勾选“**每次下载前询问**”，则可以在每次下载图片时手动选择下载路径。

**Comment by Abingbo** [comment]
好的，懂了，谢谢您的回复
