### ISSUE TITLE
Suggest adding support for image link in GitHub source 

### ISSUE THREAD

**Issue by HCW-Dev** [Mr-VincentW/PhotoShow#56]
目前版本似乎無法解析 GitHub 專案裡的圖片連結（如下圖），不確定是原本就不支持還是我環境的問題。

![Example](https://user-images.githubusercontent.com/83523727/179868009-e3b14ffb-7877-4244-8103-66b369a1b695.png)

Thank you @Mr-VincentW for creating this useful extension.

**Comment by Mr-VincentW** [comment]
Thanks for your feedback. This could be a bug and will be addressed later. I'll let you know the progress here.

**Comment by Mr-VincentW** [comment]
This has been done in update 4.18 on Oct 9, 2022.
