### ISSUE TITLE
堆糖相关

### ISSUE THREAD

**Issue by ouoluo** [Mr-VincentW/PhotoShow#59]
https://www.duitang.com/people/?id=17078423  获取原图过程
点击图片 https://c-ssl.dtstatic.com/uploads/blog/202207/21/20220721140816_7e28e.thumb.300_300_c.jpg_webp
点击放大
再点击 https://c-ssl.dtstatic.com/uploads/blog/202207/21/20220721140816_7e28e.thumb.1000_0.jpg
再放大 原图 https://c-ssl.duitang.com/uploads/blog/202207/21/20220721140816_7e28e.jpg
可以支持预览原图吗

**Comment by ouoluo** [comment]
https://c-ssl.dtstatic.com/uploads/blog/(.*).thumb(.*)jpg(.*)
重定向至  https://c-ssl.duitang.com/uploads/blog/$1.jpg
duitang.com/uploads/.*\.thumb\.   |   '@'.replace(/\.thumb.*\./, '.')
^(https?://[^\./]+.duitang.com/uploads/.*?)\.thumb\..*?(\.[a-z]{2,5})${#^_^#}$1$2

**Comment by Mr-VincentW** [comment]
如果仍需支持，请保持 issue open.
