### ISSUE TITLE
体验很不错 但是能增加个这种功能么

### ISSUE THREAD

**Issue by lhj5426** [Mr-VincentW/PhotoShow#6]
能增加这种功能吗 
![image](https://user-images.githubusercontent.com/30548000/88365836-dc7c5100-cdb9-11ea-9026-61ab3ec86611.png)

显示图片的分辨率 

你开发带 这个插件弹出的图片的动画 很丝滑 比 老牌子的 Imagus  生硬弹出 从视觉上 来说 提升是 感官上的体验 就是可能是因为 用了很多年的 Imagus 已经习惯了 图片弹出附带上 图片的具体分分辨率 了 用你这个 没有分辨率提示 还是有点小难受 
所有要是不麻烦的话 能否把 显示图片并且可以显示图片的分辨率 纳入您的开发日程里呢 
还有 还有
还有可以支持下的大众化的本子网站么 什么 ehentai  EXhentai这种
这种网站确实有需要 放大的需要
![image](https://user-images.githubusercontent.com/30548000/88366267-4f39fc00-cdbb-11ea-84f1-4d3cf62fe447.png)
![image](https://user-images.githubusercontent.com/30548000/88366280-582acd80-cdbb-11ea-973f-1c926398b461.png)
用了你这个 之后 喜欢上这个弹出的动画 一用上就回不去了- -  所有 恳请 也希望能支持下这2个网站 哈

**Comment by Mr-VincentW** [comment]
感谢反馈。

可以想到的是，并不是所有用户都喜欢在图片上方或者某个位置显示图片的分辨率，而目前浮图秀的弹出面板已经“满载”，没有更多的空间添加新的开关用以控制此显隐（否则会出现丑陋的滚动条）。与此同时，浮图秀目前仍在进行较大的重构，未来会考虑单独添加一个配置页面来放置各种配置项。此重构预计需要比较长的时间（工作繁忙...）。所以，我将保持此 issue open，直至最后决定是否添加显示分辨率的功能。

未来浮图秀预计将支持所有网站，按照一定的默认规则尝试获取大图；但依然不能保证在所有网站都能有效地工作。所以如果有需要特别支持的网站，您可以在此罗列出来，我将尝试手动适配。此项需求可以在近期优先完成，不需要等待大的版本变更。

谢谢。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/88408471-2ee35f00-ce06-11ea-8fd1-569b771d9ec8.png)
![image](https://user-images.githubusercontent.com/30548000/88408484-33a81300-ce06-11ea-8591-53b4db3c98e7.png)

 开发者老哥说的是 如果可能弄个像这样的开关 放在 图片的某个角落其实就行
老厂牌 的 Imagus  默认也不是一开始就有显示的 都是再设置里可以设置的 喜欢的用户就开启 不喜欢的就不开启 不管怎么说
期待您 的新版本 虽然是个可有可无的功能的 不过还是希望可以有

**Comment by Mr-VincentW** [comment]
浮图秀已于版本 4.6.0.0 起支持显示大图分辨率，在配置面板中替代了无甚必要的“图标显示”并移除了相关功能。
