### ISSUE TITLE
使用火狐浏览器观看b站直播影响显示效果

### ISSUE THREAD

**Issue by 89x98** [Mr-VincentW/PhotoShow#61]
不知道为什么会对视频画面产生影响，在b站任意直播间，开启浮图秀的话，当浏览位置在最顶层时，直播画面整体就被变亮一层。往下滚动一点的话，画面这层变亮的效果就消失了。仅在Firefox上测试有这个问题，测试edge正常

位于最顶层时的效果
![图片](https://user-images.githubusercontent.com/92101535/184606647-db6b71a1-ee3e-4d80-994f-6516a20c0572.png)

向下滚动一点之后的效果
![图片](https://user-images.githubusercontent.com/92101535/184606735-7d49fc09-e266-4dd4-bf57-1d7db63abbb7.png)

**Comment by 89x98** [comment]
今天发现b站的视频也会受影响，但向下滚动不会变暗，是全程都在变亮一层的

**Comment by Mr-VincentW** [comment]
感谢反馈，我未能复现上述问题。烦请附上具体链接及你的浏览器版本、浮图秀版本，以便排查。谢谢。

**Comment by 89x98** [comment]
> 感谢反馈，我未能复现上述问题。烦请附上具体链接及你的浏览器版本、浮图秀版本，以便排查。谢谢。

火狐104.0，浮图秀4.17.1
测试视频地址 https://live.bilibili.com/3
刚才又试了一下，疑似也与b站的播放器内核版本有关。播放视频时内核变动较多，可能是在内部做灰度测试。

可复现问题的播放器内核版本如下：
在直播画面右键查看当前播放器版本为 Bilibili HTML5 Live Player 3.6.76
在视频画面右键查看播放器版本为 3.17.2-rc.7949.0-8364bddc

当视频播放器内核为 3.18.2-bf561288时，反而没有问题了。所以可以优先考虑以直播间的情况为准，直播间的播放器更新频率似乎低一些。

**Comment by Mr-VincentW** [comment]
按照你所给的测试地址及其他相关信息，我依然未能复现你所遇到的问题。请进一步确认是否有其他浏览器插件可能产生此影响。

**Comment by 89x98** [comment]
> 按照你所给的测试地址及其他相关信息，我依然未能复现你所遇到的问题。请进一步确认是否有其他浏览器插件可能产生此影响。

复现不了也没办法了，我专门新装了一个火狐也是这样，只装了浮图秀。应该不是插件冲突
