### ISSUE TITLE
Feature request: Disable PhotoShow for an image once it has been dynamically enlarged by the website

### ISSUE THREAD

**Issue by desbest** [Mr-VincentW/PhotoShow#63]
Hello I have a feature request.

I would like PhotoShow to be automatically disabled for an image once it has been dynamically enlarged by the website.

See here for an example web page.
https://www.jqueryscript.net/demo/jQuery-Plugin-For-Image-Lightbox-with-Zoom-Effect-Zoomify/

If I click the image for it to zoom in, I would like PhotoShow to recognise that the image has immediately gotten dynamically larger, to then disable the PhotoShow for the image, once it has been zoomed in by the user.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This has been fixed with update 4.18.
