### ISSUE TITLE
Behance无法直接保存

### ISSUE THREAD

**Issue by RoasDuck** [Mr-VincentW/PhotoShow#64]
插件版本：: 4.17.1

使用浏览器：Microsoft Edge 版本 104.0.1293.70 (正式版本) (64 位)

只能预览和保存项目的封面，在打开的项目页面不能保存，只能点击打开项目的永久链接，在永久链接页面才能保存

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题将随更新 4.18 修复。
