### ISSUE TITLE
豆瓣用户头像不显示原图吗

### ISSUE THREAD

**Issue by xivi1839** [Mr-VincentW/PhotoShow#65]
豆瓣用户头像不显示原图吗，点开原图还是小图

**Comment by Mr-VincentW** [comment]
烦请附上出问题页面的具体链接以便排查，谢谢。

**Comment by xivi1839** [comment]
随便找个用户点开，它的头像不显示大图，
https://www.douban.com/people/43826791/?_i=4694481W6av4Jv

**Comment by xivi1839** [comment]
还是它本身就是小头像

**Comment by Mr-VincentW** [comment]
浮图秀在豆瓣所显示的用户头像已经是该用户已知的最大尺寸头像。如果该头像尺寸不大于页面所展示缩略图的尺寸，则浮图秀不展示大图。
