### ISSUE TITLE
Breaks XDA clicking attachement

### ISSUE THREAD

**Issue by Fred-Vatin** [Mr-VincentW/PhotoShow#66]
Firefox | OS | Extension
------- | ---- | ---- 
104.0.1   | Win 10 | 4.17.1

Visit this [page](https://forum.xda-developers.com/t/rom-11-0_r58-jaguar-oneplus-6-official-v23-updated-august-8-2022.4224171/#post-84369119) as an example. When hovering an attachment, the cursor is not the hand. You can NOT click it to load it.

![image](https://user-images.githubusercontent.com/22337329/188393904-39bed03a-c36b-4cb9-9dd8-42313ff0d0f7.png)

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This will be fixed with update 4.18.
