### ISSUE TITLE
希望适配萌娘百科

### ISSUE THREAD

**Issue by Jiang10086** [Mr-VincentW/PhotoShow#68]
[萌娘百科](https://zh.moegirl.org.cn/)是一个大陆的 ACG 百科网站，其预览图往往是小图

以[辉夜大小姐 FANBOOK 条目](https://zh.moegirl.org.cn/辉夜大小姐想让我告白～天才们的恋爱头脑战～#FANBOOK)为例，其小图链接为 https://img.moegirl.org.cn/common/thumb/4/4e/辉夜大小姐想让我告白_公式Fanbook.jpg/100px-辉夜大小姐想让我告白_公式Fanbook.jpg
原图直链为 https://img.moegirl.org.cn/common/4/4e/辉夜大小姐想让我告白_公式Fanbook.jpg

由[图像详情页面](https://zh.moegirl.org.cn/File:辉夜大小姐想让我告白_公式Fanbook.jpg)得知其还有多个分辨率版本：
宽为168px：https://img.moegirl.org.cn/common/thumb/4/4e/辉夜大小姐想让我告白_公式Fanbook.jpg/168px-辉夜大小姐想让我告白_公式Fanbook.jpg
宽为420px：https://img.moegirl.org.cn/common/thumb/4/4e/辉夜大小姐想让我告白_公式Fanbook.jpg/420px-辉夜大小姐想让我告白_公式Fanbook.jpg
宽为717px：https://img.moegirl.org.cn/common/thumb/4/4e/辉夜大小姐想让我告白_公式Fanbook.jpg/717px-辉夜大小姐想让我告白_公式Fanbook.jpg

猜测其规则是：
小图地址多一个“thumb”，最后一段的构成是“文件名/宽度-文件名“，而原图最后一段是文件名。

我并不会变编程，也不知道上述信息能不能帮到开发者😂
谢谢！

**Comment by Mr-VincentW** [comment]
感谢反馈，将随更新 4.18 支持该网站。
