### ISSUE TITLE
仓库网站支持

### ISSUE THREAD

**Issue by bai12123** [Mr-VincentW/PhotoShow#71]
1.作者你好，对于cangku.icu域名已经被封，现已经更换为cangku.life.仓库站时常会更换域名，但都是cangku.*这种形式。我查看代码，只支持了cangku.icu这个域名。能否添加支持cangku.*这种形式，不然每次换域名我都要来反馈。

2.暂时在cangku.life未适配，仅提供基本支持的情况下，我做个记录。在主页可以找到如图所示的帖子《指环王：力量之戒》（点击分类-影视，也可以找到），帖子封面浮图和帖子里的图片清晰度不一致，帖子里的要清晰很多。我不知道是封面只能设置这个清晰度（类似上传大小限制导致清晰度降低），还是未能获取到更清晰的图片。等适配好后我再比较一下。
![00  ：14  ：12 ](https://user-images.githubusercontent.com/99849852/196047085-a6804f88-bfd5-44de-a2cb-35c49fa17b33.png)

**Comment by Mr-VincentW** [comment]
感谢反馈，浮图秀已于更新 4.19 开放支持所有 cangku.* 格式的域名。
