### ISSUE TITLE
bug：启用会导致网页的悬停显示在鼠标移动开自动收回

### ISSUE THREAD

**Issue by RoasDuck** [Mr-VincentW/PhotoShow#72]
启用后会导致网页的悬停显示页面在鼠标移动开自动收回，比如图中爱奇艺的视频选集，鼠标一移开集数页面就收回，导致无法选集
![image](https://user-images.githubusercontent.com/90942401/197223025-e3ef83ac-d883-40ed-8795-a60d1fb5330c.png)

**Comment by Mr-VincentW** [comment]
感谢反馈，此问题已于更新 4.20.1 中修复。
