### ISSUE TITLE
在有背景图的网页选中文字并Ctrl+C，会自动复制背景图地址

### ISSUE THREAD

**Issue by reoLantern** [Mr-VincentW/PhotoShow#73]
就无法复制文字了。如果复制图片地址的快捷键能支持修改就好了，我可以修改成Shift+C之类的

**Comment by Mr-VincentW** [comment]
感谢反馈，自定义快捷键的功能预计会在未来完成。浮图秀已于更新 4.19 最大限度修复了对选中文本的复制操作的影响。
