### ISSUE TITLE
建议：能否添加浮图的尺寸过滤功能？小的icon/头像类图标不浮图；

### ISSUE THREAD

**Issue by wym1ng** [Mr-VincentW/PhotoShow#74]
目前有的功能：
当缩略图尺寸超过窗口面积的25%时，不激活图片预览

但有的图片过小同样显示，如淘宝PC端新版界面，鼠标移到“手机购买”的二维码上方，本自动悬浮出大的二维码，可浮图秀却把小小的二维码icon方法，遮挡住二维码导致无法扫码了；
场景链接如：https://item.taobao.com/item.htm?id=655240459126

另外在部分网站后台，一般右上角的"个人中心"显示头像的，本想进入个人中心，浮图秀却放大显示原图，遮挡住“个人中心”的弹窗，无法进一步点击操作，被折磨过几次；
忘了具体哪些网站，若开发者想了解场景，只能以后遇到复现再补充；

**Comment by Mr-VincentW** [comment]
感谢反馈。您可以在浮图秀展示大图时，通过 Esc 键将大图浮层临时关闭，以便于在您所描述的情况下正常使用页面原有功能。谢谢。
