### ISSUE TITLE
微博图片TAB查看高清大图被拒绝访问

### ISSUE THREAD

**Issue by hostSugar** [Mr-VincentW/PhotoShow#77]
![image](https://user-images.githubusercontent.com/3805562/205529615-ca491317-8aa1-41bf-80db-3847a450f7e2.png)

### 在上图微博图片 Tab 查看[高清图片]( https://wx4.sinaimg.cn/original/006DBM5bly1h8sl8h4i7vj318g1jk4qp.jpg) ，显示下图提示。估计微博限制了 referer 访问，不知道是否有解决方案？

![image](https://user-images.githubusercontent.com/3805562/205529580-018f8bd0-1858-4543-9aa6-ea0aad63e39b.png)

**Comment by Mr-VincentW** [comment]
感谢反馈，已于更新 4.19.1 修复此问题，敬请期待各浏览器应用市场审核后上架。
