### ISSUE TITLE
视图模式 全景行为改变或增加一种模式

### ISSUE THREAD

**Issue by baibai92** [Mr-VincentW/PhotoShow#8]
开发者你好，我想为浮图秀提个建议，能采纳的话不胜感激

在我使用过程中，有些分辨率较大的图片显示总是不那么完整，没有一体感。例如pixiv，bilibili，乃至您主页自述文件上的蓝色图片，有些本身就是分辨率很大的图片，无论如何移动页面，旁侧空间也无法完整的呈现整个图片，需要移动鼠标或者按键来移动查看细节，或者有些可以呈现整张，但是分辨率缩小了，浮现出来的反而没有原先显示的大，画面复杂的图片细节呈现仍不完美。

我的想法是全景模式改变或增加一种模式：当鼠标悬停在图片上时，分辨率较大的图片，旁侧空间不够，预览浮层覆盖图片本身，完整呈现整张图片。

**Comment by Mr-VincentW** [comment]
感谢您的反馈。

浮图秀被定义为一个轻量级的大图显示插件，并不希望对用户浏览页面产生过多干扰。所以浮图秀的交互模式被定义为：鼠标移过缩略图时显示大图，移出即关闭；同时，为不干扰原页面内容并保证鼠标交互，浮图秀的大图预览框不会覆盖原缩略图。

这便带来一个问题：如果原页面中的“缩略图”本身尺寸就比较大，占据了页面大部分空间，则浮图秀可用于展示“大图”的空间就比较有限甚至比原“缩略图”还小了。

浮图秀的“自动”模式旨在利用页面最大可用空间完整展示“大图”，在需要时会对原图进行缩小以适配预览框尺寸；“全景”模式则会按原图尺寸展示“大图”，但因预览框尺寸有限，此时可能需要用户通过鼠标或键盘的交互来卷动原图在预览框中的可见区。浮图秀并不支持一种模式，可以按原始分辨率完整展示大图——事实上也不可能保证存在这样模式，因为总会有图片比用户的显示器可用分辨率大。

至于覆盖全页面展示大图的显示模式，由于交互较“重”，对用户浏览原页面干扰较大，浮图秀暂时不会支持。但一个类似的方案已经在构想中，预期会在未来版本中予以实现。

谢谢。

**Comment by baibai92** [comment]
感谢你的说明，让我理解了你的理念，同时让我发现自己疏忽的地方。既然侧重交互大于看图，那么对于缩略图本身尺寸比较大的，旁侧空间不足以显示原图尺寸，使得浮图秀展示的比原缩略图还小是否有必要。一则展示小图不如看缩略图，二则预览浮层会遮挡其他地方。
是否也可以实现，预览浮图比缩略图大时再展示
