### ISSUE TITLE
Reddit list image background

### ISSUE THREAD

**Issue by Mte90** [Mr-VincentW/PhotoShow#81]
Go to this page https://www.reddit.com/r/GothamKnights/ and put the mouse on the image background with violet bricks and you will get the photoshow image.
This shouldn't happen as it is just a background for the page and the whole sub.

**Comment by Mr-VincentW** [comment]
Thanks for your feedback. For some users, viewing and downloading images that are used for decorative purposes on a webpage are also their needs. However, I'm considering adding a toggle for tailoring this behaviour so please stay in tune and wait for further updates of PhotoShow. Thanks and happy new year!

**Comment by Mte90** [comment]
Happy new year to you, I understand that is helpful to have that but as you can see in this case creates a lot of problems navigating in that page as example.

**Comment by Mr-VincentW** [comment]
Atm you can try setting an assistant key via "Activation Mode" so that PhotoShow only display the HD images when you explicitly ask it to.

**Comment by Mr-VincentW** [comment]
Hi, just a quick update: PhotoShow now includes a setting to choose which thumbnail types it should respond to. For this issue, you can try unchecking "**Backgrounds**" from the list:
![image](https://github.com/user-attachments/assets/b0a3074e-7d2e-44ec-b4f5-fbfa260a45f8)

Thanks again for your support!
