### ISSUE TITLE
在JavBus里面图片还是无法预览！

### ISSUE THREAD

**Issue by cc19264997** [Mr-VincentW/PhotoShow#82]
如图，是JAVBUS的原地址，不是免翻。

![QQ图片20230104005305](https://user-images.githubusercontent.com/25716656/210403408-a8174177-db10-4ad0-bd3c-cd4fcf1eb3df.png)

系统：Windows10 LTSC 2021
浏览器：Firefox108/chrome108（都一样）
扩展版本：浮图秀 v4.19
使用代理：v2rayN v6.0.0(测试无论是全局还是绕过大陆都是这样)

很喜欢这个软件，希望下版本能够解决！最后祝作者新年快乐~

**Comment by Mr-VincentW** [comment]
谢谢，新年快乐！
烦请附上相应链接，我并不知道该网站“原地址”是什么。
另外，由于 Chrome 应用商店要求，浮图秀需要做出较大更新才能继续发布（Chrome 插件换代升级），所以下一次更新预计会比较晚。

**Comment by cc19264997** [comment]
永久域名：https://www.javbus.com/
防屏蔽地址：https://www.seejav.life/
防屏蔽地址：https://www.seejav.me/
防屏蔽地址：https://www.javsee.in/

![O7NJ4X`J @3N$82VN~6U_NC](https://user-images.githubusercontent.com/25716656/210488652-a010d738-ee8e-453b-97da-659cf5ce0c1a.png)

**Comment by cc19264997** [comment]
https://www.javbus.com/





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-VincentW/PhotoShow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 上午7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mr-VincentW/PhotoShow] 在JavBus里面图片还是无法预览！ (Issue #82)





 
烦请附上相应链接，我并不知道该网站“原地址”是什么。

**Comment by cc19264997** [comment]
已知无法显示的位置
![1](https://user-images.githubusercontent.com/25716656/210489153-d148f377-d2c4-496f-afef-b6b830747d95.png)
![2](https://user-images.githubusercontent.com/25716656/210489158-d879e8b8-2f8f-43c0-a987-81b00d203e77.png)
![3](https://user-images.githubusercontent.com/25716656/210489162-e5ee40a2-8ddc-4189-9fe0-d79d1be0d8da.png)

**Comment by Mr-VincentW** [comment]
由于 Google 推迟了应用商店插件协议更新，浮图秀得以发布新的版本 4.20.0 并完成了对您所提供的网站的支持。谢谢。
