### ISSUE TITLE
addon won't work for images with uppercase extension

### ISSUE THREAD

**Issue by Kyogre** [Mr-VincentW/PhotoShow#83]
If image has uppercase extension (e.g. `.PNG` instead of `.png`) PhotoShow won't work with it for me.
Maybe affects not only PNG, but other extensions too.
You can test with file `ICDstart-option.PNG` from https://github.com/MicrosoftDocs/windows-itpro-docs/tree/main/windows/deployment/images

**Comment by Mr-VincentW** [comment]
Thanks for your feedback, this might only be a specific issue for Git, I'll check it later and let you know once it's fixed.

**Comment by Mr-VincentW** [comment]
This has been fixed in update 4.20.0, thanks.
