### ISSUE TITLE
部分主流视频网站的悬停预览条功能会让浮图秀被顶掉

### ISSUE THREAD

**Issue by fengmingchoy** [Mr-VincentW/PhotoShow#85]
现在油管及B站的主页都开启了这项功能，当使用鼠标悬停在一个选项卡几秒后，会自动弹出视频预览拖动条，此时浮图秀会被顶掉，作者能让针对这类网站修复这个功能吗？即浮图秀不会被弹出的预览拖动条顶掉。

**Comment by Mr-VincentW** [comment]
感谢反馈，浮图秀会在后续版本中尝试修复此问题。不过由于 Chrome 应用商店更新插件版本（换代升级），浮图秀需要做出比较大的改动才能继续发布，所以预计下次发布更新会比较完，谢谢。

**Comment by Mr-VincentW** [comment]
由于 Google 推迟了应用商店插件协议更新，浮图秀得以发布新的版本 4.20.0 并修复了您所描述的问题。谢谢。
