### ISSUE TITLE
不能保存图片

### ISSUE THREAD

**Issue by xivi1839** [Mr-VincentW/PhotoShow#87]
人物，无法提取保存图片

https://dizilah.com/show/yargi/cast

**Comment by Mr-VincentW** [comment]
感谢反馈。由于 Chrome 应用商店的发布策略更新，浮图秀短期内无法更新版本。我将保持此 issue open 直到浮图秀完成重构并修复对此网站的支持。谢谢。

**Comment by xivi1839** [comment]
还有这个：https://www.imdb.com/title/tt3521192/mediaindex/?ref_=tt_mv_close

**Comment by Mr-VincentW** [comment]
> 还有这个：https://www.imdb.com/title/tt3521192/mediaindex/?ref_=tt_mv_close

烦请附上更具体的问题描述，我个人测试未发现浮图秀在此页面工作异常。谢谢。

**Comment by Mr-VincentW** [comment]
This has been fixed in update 4.20.0, If you still have issues with IMDB, please open another ticket. Thanks.
