### ISSUE TITLE
Can't download attachments on web-zones.ru when addon active

### ISSUE THREAD

**Issue by Kyogre** [Mr-VincentW/PhotoShow#89]
When Photoshow is active, I can't download attachment from https://web-zones.ru/threads/sinij-ehkran-pri-zapuske-virtualbox-na-windows-10-pri-ustanovlennoj-kriptopro-csp.3604/.
Nothing happens when I click on attachment button (blue zip icon in big square), Photoshow hides the download link.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback.
Due to some platform changes in Chrome Webstore, PhotoShow can not publish new versions recently. I'll keep this issue open until it's fixed and the new version's published.

**Comment by Mr-VincentW** [comment]
This has been fixed in update 4.20.0, thanks.
