### ISSUE TITLE
预览浮图尺寸比缩略图大时展示

### ISSUE THREAD

**Issue by baibai92** [Mr-VincentW/PhotoShow#9]
感谢你上个问题的说明，让我理解了你的理念，同时让我发现自己疏忽的地方。既然侧重交互大于看图，那么对于缩略图本身尺寸比较大的，旁侧空间不足，使得浮图秀展示的比原缩略图还小是否有必要（预览浮图全显示出来，不需要卷动的图，自动模式下）。一则展示小图不如看缩略图，二则预览浮层会遮挡其他地方。
是否也可以实现，预览浮图比缩略图尺寸大时再展示

**Comment by Mr-VincentW** [comment]
感谢您的补充，这是一个好主意！事实上浮图秀已经在某些网页“手动”做了这样的“屏蔽”，但您的补充提供了另外一个思路，使得这个过程可以自动完成。此功能同样将留待后续版本实现并将允许用户配置。

谢谢。

**Comment by baibai92** [comment]
不客气，同样也是为了自己和网友用上更好用的软件。期待您的船新版本
