### ISSUE TITLE
Option to disable antialiasing of image

### ISSUE THREAD

**Issue by Kyogre** [Mr-VincentW/PhotoShow#90]
Will be great to have option do turn off antialiasing/smoothing/blurriness of image.
As we can see on screenshot below: the image opened in tab is clear unlike the image previewed via Photoshow.

![comparison of image smoothing](https://user-images.githubusercontent.com/2260980/215275437-65f44d3a-f967-4c78-b1b3-fd35794f59d8.png)
FYI Don't pay attention at the red square - it is just a part of image itself, it is not related to this issue.

Also there is [Imagus](https://addons.mozilla.org/ru/firefox/addon/imagus/) addon which has the same feature as Photoshow but shows wonderfully clear (not smoothed) image.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. This might be due to the way how images are rendered in the popup where Chrome has a known issue that causes blurry images. If you can find some other examples on a page that I can visit, it'd be greatly helpful for me to fix and test it. Cheers.

**Comment by Kyogre** [comment]
> where Chrome has a known issue that causes blurry images

FYI I am using Firefox.

You can test on the image in this issue. Compare the quality of preview of that image in Photoshow and Imagus. My comparison:

### Imagus:

![imagus](https://user-images.githubusercontent.com/2260980/215312459-7cc14b47-5937-4006-bc20-bc977e5653d7.png)

### Photoshow:

![photoshow](https://user-images.githubusercontent.com/2260980/215312461-55a8243f-a722-4ee9-9e3f-0805d87ae068.png)

**Comment by Mr-VincentW** [comment]
Thanks, I'll follow up with this.

**Comment by Mr-VincentW** [comment]
A new setting item "IMAGE ANTI-ALIASING" has been added in update 4.20.0 with which you can turn on/off the feature. Thanks.
![image](https://user-images.githubusercontent.com/54405631/216804742-a468c088-42c6-48d4-8ee7-0e7797f1c7b5.png)
