### ISSUE TITLE
Don't work in fb

### ISSUE THREAD

**Issue by davidp88** [Mr-VincentW/PhotoShow#91]
In a facebook gallery[https://www.facebook.com/media/set/?set=a.6037721156314357&type=3](url),hover on any thumbnail it doesn't zoom image

**Comment by Mr-VincentW** [comment]
Thanks, FB updates its website quite often, I'll check this out later.

**Comment by Mr-VincentW** [comment]
This bug has been fixed in update 4.20.0.
