### ISSUE TITLE
Save image if mouse is anywhere

### ISSUE THREAD

**Issue by davidp88** [Mr-VincentW/PhotoShow#92]
It should save an image after pressing S even if the mouse pointer is anywhere(not on the image)

**Comment by Mr-VincentW** [comment]
It should be doing so, though sometimes the download process may fail (due to network condition, access permission, etc.) where PhtoShow handles silently since as you said - user focus may have already moved onto someting else after they triggered download.

**Comment by davidp88** [comment]
It's not saving when pointer is anywhere,tested twice

**Comment by Mr-VincentW** [comment]
Please attach some links and guidelines for replicating this issue, thanks.

**Comment by davidp88** [comment]
[https://www.listal.com/viewimage/8357781](url) In the image(link given) keep the mouse pointer not on the image and press S,it doesn't saves the image.
