### ISSUE TITLE
此网站图片保存不了

### ISSUE THREAD

**Issue by xivi1839** [Mr-VincentW/PhotoShow#93]
这个网站的图片保存不了：

https://www.tvpaket.com.mk/%d0%be%d1%81%d1%83%d0%b4%d0%b0-%d0%b7%d0%b0-%d0%b0%d1%85%d0%bc%d0%b5%d1%82%d0%b8-%d1%81%d0%bf%d0%be%d1%80%d0%b5%d0%b4-%d0%ba%d0%be%d1%98-%d1%82%d0%b5%d0%bb%d0%bc%d0%b0-%d0%b8-%d0%b0%d0%bb%d1%84%d0%b0/

**Comment by Mr-VincentW** [comment]
感谢反馈。我没有发现该网页提供比页面上所展示的缩略图分辨率更高的图片，因此浮图秀在该网站大多数图片上并不展示大图浮层。但图片下载功能并未失效，您依然可以通过快捷键“**S**”或右键菜单下载图片。
如有其他，请补充说明，谢谢。
