### ISSUE TITLE
Image enlargement on Instagram Stories does not work

### ISSUE THREAD

**Issue by antarn88** [Mr-VincentW/PhotoShow#95]
I use Google Chrome v110 on Windows 11.

The steps:

- I login to Instagram.
- Stories appear at the top, I click on one.
- I hover the cursor over the image and nothing happens.

It could also work for Story videos.

**Comment by Mr-VincentW** [comment]
Thanks for your feedback. I'm not on Windows 11 so cannot exactly replicate your environment. However, normally it's unlikely to be an OS-related issue. PhotoShow works for me on Ins. Can you please check if you have accidentally disabled PhotoShow for Ins in its settings or maybe you have **"ACTIVATION EXEMPTION"** on while you were browsing Ins in a small browser window?

Also, PhotoShow doesn't support viewing videos at the moment, you can get a video cover preview instead though.

Feel free to attach more details of your issue or reach out to me via email. Thanks.

**Comment by antarn88** [comment]
It works everywhere within instagram, except for stories!
It's not disabled, and I tried it with and without "ACTIVATION EXEMPTION"! I have attached a picture.

![insta](https://user-images.githubusercontent.com/61657422/218307475-9abb49c2-2ce2-45e0-bd12-2c2ec8b39f9b.png)

**Comment by Mr-VincentW** [comment]
Thanks for the supplementary. I'll address this issue later and let you know the result.

**Comment by Mr-VincentW** [comment]
Thanks again for your feedback. This issue has been fixed in update 4.20.1.

**Comment by antarn88** [comment]
Thanks for the fix.

However, the enlarged image is not always the highest resolution.
For example, when I save images with this, sometimes they are much higher resolution:

https://www.storysaver.net/

**Comment by Mr-VincentW** [comment]
Thanks, I'll need to investigate how this works a bit.

**Comment by Mr-VincentW** [comment]
Similar to #98, PhotoShow will not rely on third-party services or Instagram platform APIs to fetch HD images at this stage. Thank you.
