### ISSUE TITLE
[Facebook] - The "More" option on the profile page is not clickable.

### ISSUE THREAD

**Issue by antarn88** [Mr-VincentW/PhotoShow#96]
The "More" option on the profile page is not clickable, if I use PhotoShow. I attached a photo.
I use Google Chrome v110 on Windows 11.

![facebook more](https://user-images.githubusercontent.com/61657422/218308721-c9ad081b-4285-4502-9ff3-f57ecc473e1b.png)

**Comment by Mr-VincentW** [comment]
Thanks, this will be fixed with the next update of PhotoShow.

**Comment by Mr-VincentW** [comment]
Thanks again for your feedback. This issue has been fixed in update 4.20.1.
