### ISSUE TITLE
Facebook buttons next/prev photos don’t work

### ISSUE THREAD

**Issue by Fred-Vatin** [Mr-VincentW/PhotoShow#97]
Firefox | OS | Extension
------- | ---- | ---- 
109.0.1 (64 bits)  | Win 10 21H2 | 4.20.0

When extension is enabled, the buttons to display next/prev photos don’t work.
![image](https://user-images.githubusercontent.com/22337329/218335920-a3a8c62d-3c1e-4fae-9520-4b78b24bcb1d.png)

You can test it [here](https://www.facebook.com/photo/?fbid=2408863712586656&set=pcb.2408867199252974).

**Comment by Mr-VincentW** [comment]
Hi Fred,

Thanks for your feedback.

This issue will be addressed with the next update of PhotoShow. I'll let you know then.

Cheers,

**Comment by Mr-VincentW** [comment]
Thanks again for your feedback. This issue has been fixed in update 4.20.1.
