### ISSUE TITLE
[Instagram] Enlarging the profile picture does not work

### ISSUE THREAD

**Issue by antarn88** [Mr-VincentW/PhotoShow#98]
I use the latest Google Chrome on Windows 11,
and enlarging the profile picture does not work on Instagram.
I attached a screenshot.

![insta](https://user-images.githubusercontent.com/61657422/220047088-1a35f485-00d7-4238-a8d8-83dc8dcf7d23.png)

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. If PhotoShow cannot find a larger pic for a certain thumbnail, the image viewer will not show up. The profile avatar on an Instagram profile page is right the case. If you know where to find a larger image for this, please let me know. Thanks.

**Comment by antarn88** [comment]
There is a page where you can download the profile picture in 1080x1080p.

https://www.save-insta.com/profile-downloader/

Unfortunately, I couldn't find a site that saves the profile picture as a larger image.

And you can remove the prefix from the end result link:
"https://www.save-insta.com/cdn/"

I hope I can somehow write an algorithm that you can use in your script.

**Comment by Mr-VincentW** [comment]
Thank you for the supplements. These third-party apps/websites might be using Instagram Platform APIs to fetch these higher-definition images which I could not find anywhere directly from Instagram itself. Doing so would be an over-hit for PhotoShow now and there might be other concerns. I'll leave PhotoShow as is for Instagram unless one day a better and easier approach to fetching these HD images shows up.

**Comment by Mr-VincentW** [comment]
Just FYI, I managed to make it work for the profile pics in update 4.21.0 as well. Enjoy it!

**Comment by antarn88** [comment]
Thanks a lot, it's good :)
The only thing is that the profile picture zoom works for the public pages I follow, but if I go to a private page that I don't follow and try to zoom from there, it doesn't work.

Do you know a fix for this?

**Comment by Mr-VincentW** [comment]
Great to know, currently I can't see a reliable way to make it work for private profiles, however, there's a workaround I can think of, less reliable but will work for now. I'll add it to the next update of PhotoShow. Thanks.

**Comment by antarn88** [comment]
###  Maybe it can still be hidden?




![icon](https://user-images.githubusercontent.com/61657422/224418302-857a3e81-0d11-46c2-b6a9-346840b8fdae.png)


This icon with this text:

You've reached the end.
You have seen all new posts from the last 3 days.

**Comment by Mr-VincentW** [comment]
PhotoShow only applies some generic rules to avoid working on these decorative/servicing items, as opposed to marking cases individually for obvious reasons. In fact, the case you mentioned is a poor implementation of Instagram as they should not use an image element here (an icon or other element with a background image is preferred, in terms of web semantics). I'll leave this as is. Thanks.

**Comment by Mr-VincentW** [comment]
Able to view profile images of private accounts since update 4.22. Cheers.

**Comment by antarn88** [comment]
I noticed a new bug.
Unfortunately Instagram Stories are broken since few days. No enlargement of the image appears at all.

**Comment by Mr-VincentW** [comment]
Looks like Ins has changed this part a bit again... gonna need a fix. Thanks.

**Comment by Mr-VincentW** [comment]
Fixed with update 4.23.0 (please refer to #120).
