### ISSUE TITLE
Avoid enlarging images that are already full-size (or close to)

### ISSUE THREAD

**Issue by alejandro5042** [Mr-VincentW/PhotoShow#99]
The extension shouldn't enlarge already enlarged pictures. It just gets in the way of the text.

For example:

![image](https://user-images.githubusercontent.com/3143819/220167979-d8d2ce7d-fcfe-4de0-851b-375c766b06cf.png)

**Comment by Mr-VincentW** [comment]
Please try ticking the "ACTIVATION EXCEPTION" settings in PhotoShow's settings popup.
![image](https://user-images.githubusercontent.com/54405631/221342609-65938949-a782-481c-b5e9-b031a89b3e40.png)
